(function(root){ root.RECON_DATABOOK_CATALOG = [
  {
    "description": "LD- LISTA DE DOCUMENTOS",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - SISTEMA DE QUALIDADE|LD C&M",
    "notes": "Documentos: \r\n*LISTA MESTRA DE DOCUMENTOS - LD - RELAÇÃO DE DOCUMENTOS C&M",
    "rowNumber": 13,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "GESTÃO DE QUALIDADE",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - SISTEMA DE QUALIDADE|GESTÃO DA QUALIDADE",
    "notes": "Documentos: \r\n*PLANO DA QUALIDADE;\r\n* ORGANOGRAMA DA QUALIDADE;\r\n*OUTROS, CONFORME NECESSIDADES DO PROJETO.",
    "rowNumber": 15,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "CONSULTA TÉCNICA - CT",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - SISTEMA DE QUALIDADE|CONSULTA TÉCNICA",
    "notes": "Documentos: \r\n* MAPA DE CONTROLE DAS CONSULTAS TÉCNICAS DE CAMPO - (SQF);\r\n* MAPA DE CONTROLE DAS CONSULTAS TÉCNICAS  - (TQF);\r\n* CONSULTAS TÉCNICAS DE CAMPO - (SQF);\r\n* CONSULTAS TÉCNICAS - (TQF);",
    "rowNumber": 17,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "AUDITORIA",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - SISTEMA DE QUALIDADE|AUDITORIA",
    "notes": "Documentos: \r\n* REGISTROS DAS AUDITORIAS INTERNAS REALIZADAS;\r\n* REGISTROS DA QUALIDADE COMO EVIDÊNCIA DE CONFORMIDADE (RELATÓRIOS, LISTAS DE VERIFICAÇÃO, REGISTROS DE INSPEÇÃO E TESTES);\r\n* RESULTADOS DE AUDITORIAS REALIZADAS PELA PETROBRAS E RESPECTIVAS TRATATIVAS;\r\n* PLANOS DE AÇÃO E EVIDÊNCIAS DE TRATAMENTO DAS NÃO CONFORMIDADES IDENTIFICADAS EM AUDITORIAS, INSPEÇÕES OU LISTAS DE VERIFICAÇÃO.",
    "rowNumber": 19,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PUNCH LIST",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - SISTEMA DE QUALIDADE|PUNCH LIST",
    "notes": "Documentos: \r\n*MAPA DE PUNCH LIST;\r\n*PUNCH LIST POR DISCIPLINAS.",
    "rowNumber": 21,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RELATÓRIO DE NÃO CONFORMIDADE - RNC/RD",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - SISTEMA DE QUALIDADE|RELATÓRIO DE NÃO CONFORMIDADE",
    "notes": "Documentos: \r\n*MAPA DE CONTROLE DE NÃO CONFORMIDADES",
    "rowNumber": 23,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RNC - RELATÓRIO DE NÃO CONFORMIDADE",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - SISTEMA DE QUALIDADE|RELATÓRIO DE NÃO CONFORMIDADE|RNC",
    "notes": "",
    "rowNumber": 25,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RD - REGISTRO DE DESVIOS",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - SISTEMA DE QUALIDADE|RELATÓRIO DE NÃO CONFORMIDADE|RD",
    "notes": "Documentos: \r\n*RD - RELATÓRIOS DE DESVIOS; TRATA-SE DE NÃO CONFORMIDADES ENCONTRADAS EM CAMPO. \r\n* MATRIZ DE RASTREABILIDADE DOS RDsDRIRs- Nº RIR - Nº RELATÓRIO DE CONCLUSÃO DO RD.\nDocumentos:\r\n*MAPA CAMINHO DATA BOOK C&M - SISTEMA DE QUALIDADE",
    "rowNumber": 27,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PROCEDIMENTOS DE FABRICAÇÃO E TESTES EM FÁBRICA",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - PROCEDIMENTOS DE EDECUÇÃO|FABRICAÇÃO E TESTES FÁBRICA",
    "notes": "",
    "rowNumber": 31,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PROCEDIMENTOS DE CIVIL E ESTRUTURAS METÁLICAS",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - PROCEDIMENTOS DE EDECUÇÃO|CIVIL E EST. METÁLICA",
    "notes": "",
    "rowNumber": 32,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PROCEDIMENTOS DE TUBULAÇÃO (FABRICAÇÃO, INSPEÇÃO, C&M E CONDICIONAMENTO)",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - PROCEDIMENTOS DE EDECUÇÃO|TUBULAÇÃO",
    "notes": "",
    "rowNumber": 33,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PROCEDIMENTOS DE VÁLVULAS (INSPEÇÃO, C&M, CONDICIONAMENTO, ETC.)",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - PROCEDIMENTOS DE EDECUÇÃO|VÁLVULAS",
    "notes": "",
    "rowNumber": 34,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PROCEDIMENTOS DE EQP. ESTÁTICOS (INSPEÇÃO, C&M E CONDICIONAMENTO)",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - PROCEDIMENTOS DE EDECUÇÃO|EQP ESTÁTICOS",
    "notes": "",
    "rowNumber": 35,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PROCEDIMENTOS DE EQP. DINÂMICOS (INSPEÇÃO, C&M E CONDICIONAMENTO)",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - PROCEDIMENTOS DE EDECUÇÃO|EQP DINÂMICOS",
    "notes": "",
    "rowNumber": 36,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PROCEDIMENTOS DE ELÉTRICA (INSPEÇÃO, C&M E CONDICIONAMENTO)",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - PROCEDIMENTOS DE EDECUÇÃO|ELÉTRICA",
    "notes": "",
    "rowNumber": 37,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PROCEDIMENTOS DE TELECOMUNICAÇÕES",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - PROCEDIMENTOS DE EDECUÇÃO|TELECOMUNICAÇÕES",
    "notes": "",
    "rowNumber": 38,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PROCEDIMENTOS DE INSTRUMENTAÇÃO (INSPEÇÃO, C&M, CALIBRAÇÃO, ETC.)",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - PROCEDIMENTOS DE EDECUÇÃO|INSTRUMENTAÇÃO",
    "notes": "",
    "rowNumber": 39,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PROCEDIMENTOS DE RECEBIMENTO, ARMAZENAMENTO E PRESERVAÇÃO",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - PROCEDIMENTOS DE EDECUÇÃO|RECEBIMENTO-ARMAZ.-PRESERVAÇÃO",
    "notes": "",
    "rowNumber": 40,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PROCEDIMENTOS DE TESTES DE CAMPO",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - PROCEDIMENTOS DE EDECUÇÃO|TESTES CAMPO",
    "notes": "",
    "rowNumber": 41,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PROCEDIMENTOS DE PINTURA",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - PROCEDIMENTOS DE EDECUÇÃO|PINTURA",
    "notes": "",
    "rowNumber": 42,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PROCEDIMENTO DE SMS_SAÚDE",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - PROCEDIMENTOS DE EDECUÇÃO|SMS SAÚDE",
    "notes": "",
    "rowNumber": 43,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PROCEDIMENTO DE SMS_SEGURANÇA",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - PROCEDIMENTOS DE EDECUÇÃO|SMS SEGURANÇA",
    "notes": "",
    "rowNumber": 44,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PROCEDIMENTO DE SMS_MEIO AMBIENTE",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - PROCEDIMENTOS DE EDECUÇÃO|SMS AMBIENTE",
    "notes": "",
    "rowNumber": 45,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PROCEDIMENTO COMUNS SMS - APLICÁVEL SIMULTANEAMENTE A MAIS DE UMA DISCIPLINA DE SMS",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - PROCEDIMENTOS DE EDECUÇÃO|SMS COMUNS",
    "notes": "",
    "rowNumber": 46,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PROCEDIMENTO DE PLANEJAMENTO",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - PROCEDIMENTOS DE EDECUÇÃO|PLANEJAMENTO",
    "notes": "",
    "rowNumber": 47,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PROCEDIMENTO DE COMISSIONAMENTO",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - PROCEDIMENTOS DE EDECUÇÃO|COMISSIONAMENTO",
    "notes": "",
    "rowNumber": 48,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PROCEDIMENTO DE QUALIDADE",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - PROCEDIMENTOS DE EDECUÇÃO|QUALIDADE",
    "notes": "",
    "rowNumber": 49,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PROCEDIMENTO CRS - COMUNICAÇÃO E RESPONSABILIDADE SOCIAL",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - PROCEDIMENTOS DE EDECUÇÃO|CRS - COMUNICAÇÃO E RESP. SOCIAL",
    "notes": "",
    "rowNumber": 50,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PROCEDIMENTO ADM. CONTRATUAL",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - PROCEDIMENTOS DE EDECUÇÃO|ADM. CONTRATUAL",
    "notes": "",
    "rowNumber": 51,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PROCEDIMENTO C&M COMUNS  - APLICÁVEL SIMULTANEAMENTE A MAIS DE UMA DISCIPLINA DE C&M",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - PROCEDIMENTOS DE EDECUÇÃO|C&M COMUNS",
    "notes": "Documentos:\r\n*MAPA CAMINHO DATA BOOK C&M - CERTIFICADOS DE QUALIDADE",
    "rowNumber": 52,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "CERTIFICADOS (Ver obsevações)",
    "databook": "UHDT-D|DATA BOOK C&M|GERAL - CERTIFICADOS DE QUALIDADE",
    "notes": "* LD - Mapa com todos os certificados contidos nessa pastinha.\r\n* Certificados gerais, que NÃO está eDigido na pastinha da disciplina.\r\nCOMO DEFINIR QUANDO O CERTIFICADO VEM PARA ESSA PASTA (GERAL) OU PARA A PASTA ESPECÍFICA DA DISCIPLINA/UNIDADE? QUESTIONE:\r\n\"Pergunta-chave: Este certificado consegue ser associado diretamente a um TAG, equipamento ou sistema ou linha? \r\nÉ solicidado no item específico do data boock?\"\r\nCaso um das respostas for Sim → Vai para a pasta da solicitada na disciplina.\r\nCASO AS DUAS SEJAM NÃO → ABRANGE A UNIDADE/ÁREA COMO UM TODO? FICA AQUI NESSA PASTA GERAL. Se ainda assim houver dúvida consulte a equipe de fiscaliação de qualidade e, ou, disciplina a qual o certifica será submetido para avaliação.\nDocumentos:\r\n*MAPA CAMINHO DATA BOOK C&M - PINTURA",
    "rowNumber": 55,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PINTURA E JATEAMENTO",
    "databook": "UHDT-D|DATA BOOK C&M|PINTURA|PINTURA E JATEAMENTO",
    "notes": "Documentos: \r\n* MAPA DE PINTURA;\r\n* RELATÓRIOS DE JATEAMENTO E  PINTURA (ESTRUTURAS METÁLICAS, TUBULAÇÃO);\r\n* RELATÓRIOS DE CONDUTIBILIDADE DE ABRASIVOS (ESTRUTURAS METÁLICAS, TUBULAÇÃO);\r\n* RELATÓRIOS DE CONTAMINAÇÃO SALINA DE SUPERFÍCIE (ESTRUTURAS METÁLICAS, TUBULAÇÃO); \r\n* RELATÓRIOS DE ENSAIO POR TRAÇÃO: PULL-OFF (ESTRUTURAS METÁLICAS, TUBULAÇÃO)",
    "rowNumber": 61,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "INSPEÇÃO E CERTIFICADOS",
    "databook": "UHDT-D|DATA BOOK C&M|PINTURA|INSPEÇÃO E CERTIFICADOS",
    "notes": "Documentos: \r\n* CERTIFICADOS DE CONSUMÍVEIS DE PINTURA;\r\n* CERTIFICADOS DE ANÁLISE (TINTA, VERNIZ E SOLVENTE);\r\n* RELATÓRIOS DE INSPEÇÃO DE PINTURA;\r\n* OUTROS, CONFORME NECESSIDADES DO PROJETO",
    "rowNumber": 63,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "QUALIFICAÇÃO DA EQUIPE_PINTURA",
    "databook": "UHDT-D|DATA BOOK C&M|PINTURA|QUALIFICAÇÃO DA EQUIPE_PINTURA",
    "notes": "Documentos: \r\n* LISTA DE PINTORES QUALIFICADOS\r\n* TODA DOCUMENTAÇÃO INERENTE A QUALIFICAÇÃO DA EQUIPE DE PINTURA.\nDocumentos:\r\n*MAPA CAMINHO DATA BOOK C&M - CIVIL",
    "rowNumber": 65,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "INSPEÇÃO DE RECEBIMENTO - RIR_CIVL E ESTRUTURA METÁLICA",
    "databook": "UHDT-D|DATA BOOK C&M|CIVIL|RIR CIVIL",
    "notes": "",
    "rowNumber": 69,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RELATÓRIOS DE INSPEÇÃO DE RECEBIMENTO - RIR_ CONCRETO-DRENAGEM",
    "databook": "UHDT-D|DATA BOOK C&M|CIVIL|RIR CIVIL|CONCRETO-DRENAGEM",
    "notes": "Documentos: \r\n* RIR CONCRETO E DRENAGEM DAS UNIDADES",
    "rowNumber": 70,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RELATÓRIOS DE INSPEÇÃO DE RECEBIMENTO - RIR_EST. METÁLICA",
    "databook": "UHDT-D|DATA BOOK C&M|CIVIL|RIR ESTRUTURA METÁLICA",
    "notes": "Documentos: \r\n* RIRs Estrutura metálica",
    "rowNumber": 72,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RELATÓRIOS DE INSPEÇÃO DE RECEBIMENTO - RIR_SUBESTAÇÃO CVL",
    "databook": "UHDT-D|DATA BOOK C&M|CIVIL|RIR CIVIL|SUBESTAÇÃO_CIVIL",
    "notes": "Documentos: \r\n* RIRs Subestação",
    "rowNumber": 74,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "ESTRUTURA METÁLICA",
    "databook": "UHDT-D|DATA BOOK C&M|CIVIL|ESTRUTURA METÁLICA",
    "notes": "Documentos: \r\n* RELATÓRIOS DE MONTAGEM / DESMONTAGEM DE ESTRUTURA METÁLICA",
    "rowNumber": 76,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "ANDAIME",
    "databook": "UHDT-D|DATA BOOK C&M|CIVIL|ANDAIME",
    "notes": "Documentos: \r\n* RELATÓRIOS DE MONTAGEM / DESMONTAGEM DE ESTRUTURA METÁLICA",
    "rowNumber": 78,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "CONCRETO - CERTIFICADOS E TESTES",
    "databook": "UHDT-D|DATA BOOK C&M|CIVIL|CONCRETO - CERTIFICADOS E TESTES",
    "notes": "Documentos: \r\n* AÇO - EMENDAS DE BARRAS DE AÇO PARA CONCRETO ARMADO (NBR 8548 E 11919)\r\n* AÇO - ENSAIO DE DOBRAMENTO (NBR 6153)\r\n* AÇO - ENSAIO DE TRAÇÃO (NBR 6152)\r\n* ADITIVOS – DENSIDADE\r\n* ADITIVOS – PH\r\n* ADITIVOS - TEOR DE CLORETOS\r\n* ADITIVOS - TEOR DE SÓLIDOS\r\n* AGREGADOS - AMOSTRAGEM REPRESENTATIVA (NBR 7216)\r\n* AGREGADOS - GRANULOMETRIA (NBR 7217)\r\n* AGREGADOS - IMPUREZAS ORGÂNICAS - AGREGADOS MIÚDOS (NBR 7220)\r\n* AGREGADOS - MASSA ESPECÍFICA E ABSORÇÃO DE ÁGUA (MIÚDO E GRAÚDO - NBRS 9776, 9777  9937)\r\n* AGREGADOS - MASSA UNITÁRIA (NBR 7251)\r\n* AGREGADOS - MATERIAL PULVERULENTO (NBR 7219)\r\n* AGREGADOS - TEOR DE ARGILA (NBR 7218)\r\n* AGREGADOS - UMIDADE SUPERFICIAL DO AGREGADO MIÚDO (NBR 9775)\r\n* ÁGUA - COMPOSIÇÃO QUÍMICA\r\n* ÁGUA - DETERMINAÇÃO DO PH\r\n* CARTA TRAÇO DO CONCRETO\r\n* CIMENTO - AMOSTRAGEM REPRESENTATIVA (NBR 5741)\r\n* CIMENTO - ENSAIO DE FINURA (PENEIRA 200 - NBR 11579)\r\n* CIMENTO - ENSAIOS DE TEMPO DE PEGA (NBR 11581)\r\n* CIMENTO - EDPANSIBILIDADE (NBR 11582)\r\n* ENSAIO DE CORPOS DE PROVA DO CONCRETO REFRATÁRIO\r\n* RELATÓRIO DE PROVA DE CARGAS ESTÁTICAS EM ESTACAS (PCE)",
    "rowNumber": 80,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "CONCRETO - SUPERESTRUTURA",
    "databook": "UHDT-D|DATA BOOK C&M|CIVIL|CONCRETO - SUPERESTRUTURA",
    "notes": "Documentos: \r\n* RELATÓRIO DE INSPEÇÃO DIMENSIONAL DE PRÉ-MOLDADOS E OUTROS;\r\n* RELATÓRIO DE INSPEÇÃO E SOLIDARIZAÇÃO DE PRÉ-MOLDADOS;\r\n* RELATÓRIO DE RESISTÊNCIA DO CONCRETO - VIGA ANELAR;\r\n* RELATÓRIO DE VERTICALIDADE DOS PILARES.",
    "rowNumber": 82,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "CONCRETO  - INFRAESTRUTURA",
    "databook": "UHDT-D|DATA BOOK C&M|CIVIL|CONCRETO - INFRAESTRUTURA",
    "notes": "Documentos: \r\n* RELATÓRIOS DE MONTAGEM REFERENTE A TODAS AS ESTRUTURAS DE CONCRETO, EDCETO DRENAGEM\r\n(BASES, PRÉ-MOLDADOS, PISO)\r\n* REGISTRO DA PINTURA IMPERMEABILIZANTE DOS BLOCOS, CINTAS, DORMENTES, MUROS; * REGISTRO DE PINTURA IMPERMEABILIZANTE DA BASE; * REGISTRO DE PINTURA IMPERMEABILIZANTE DA FUNDAÇÃO DOS PONTILHÕES; * REGISTRO DE PINTURA IMPERMEABILIZANTE DAS FUNDAÇÕES; * REGISTRO DE PINTURA IMPERMEABILIZANTE DOS DORMENTES; * RELATÓRIO DE CONFORMIDADE DA BASE - LOCAÇÃO E DIMENSÕES REAIS DA BASE; * RELATÓRIO DE CONFORMIDADE DA LOCAÇÃO - DIMENSÕES REAIS DA BASE\r\n* RELATÓRIO DE CONFORMIDADE DA LOCAÇÃO - DIMENSÕES REAIS DA INFRAESTRUTURA; * RELATÓRIO DE CONTROLE ESTATÍSTICO DO GROUT; * RELATÓRIO DE COORDENADAS DE LOCAÇÃO (ESTACAS/BASES CIVIS/SAPATAS, OUTRAS); * RELATÓRIO DE CRAVAÇÃO DE ESTACAS (RCE); * RELATÓRIO DE ENSAIO DE INTEGRIDADE DE ESTACAS (PIT); * RELATÓRIO DE ENSAIOS DE DETERMINAÇÃO DA RESISTÊNCIA À COMPRESSÃO DO GROUT; * RELATÓRIO DE INSTALAÇÃO DE REFERÊNCIA DE NÍVEL PROFUNDA (RNP); * RELATÓRIO DE LIBERAÇÃO DE ESTACAS (RIT); * RELATÓRIO DE LOCAÇÃO DE CHUMBADORES; * RELATÓRIO DE NIVELAMENTO DA BASE; * RELATÓRIO DE RECEBIMENTO DA BASE; * RELATÓRIO DE REFERÊNCIAS DE NÍVEL E COORDENADAS DE ÁREA/BASE; * RELATÓRIO DE RESISTÊNCIA DO CONCRETO DE FUNDO; * RELATÓRIO DE RESUMO DE ARRASAMENTO DE ESTACAS (RAE); * RELATÓRIO DE RESUMO DE CRAVAÇÃO DE ESTACAS (RCE); * RELATÓRIO DE SONDAGENS COMPLEMENTARES; * RELATÓRIOS DE INSPEÇÃO DE EDCENTRICIDADES EM ESTACAS (RIEE).",
    "rowNumber": 84,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "DRENAGEM",
    "databook": "UHDT-D|DATA BOOK C&M|CIVIL|DRENAGEM",
    "notes": "Documentos: \r\n* RELATÓRIOS DE MONTAGEM DO SISTEMA DE DRENAGEM\r\n(CAIDAS COLETORAS, CAIDAS DE PASSAGEM, CAIDAS DE INSPEÇÃO, CAIDA DE RALO, CAIDA DE AREIA, CAIDA DE PUMP-OUT)",
    "rowNumber": 86,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "CIVIL SUBESTAÇÃO",
    "databook": "UHDT-D|DATA BOOK C&M|CIVIL|SUBESTAÇÃO_CIVIL",
    "notes": "Documentos: \r\n* RELATÓRIOS DE MONTAGEM CIVIL\r\n(FACHADA, TELHADO, PISO, PORTAS, JANELAS, ALVENARIA, ACABAMENTOS, ETC.)",
    "rowNumber": 88,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PAVIMENTAÇÃO E ARRUAMENTO",
    "databook": "UHDT-D|DATA BOOK C&M|CIVIL|PAVIMENTAÇÃO E ARRUAMENTO",
    "notes": "Documentos: \r\n* RELATÓRIOS DE MONTAGEM CIVIL\r\n(FACHADA, TELHADO, PISO, PORTAS, JANELAS, ALVENARIA, ACABAMENTOS, ETC.)",
    "rowNumber": 90,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "QUALIFICAÇÃO DA EQUIPE_CIVIL",
    "databook": "UHDT-D|DATA BOOK C&M|CIVIL|QUALIFICAÇÃO DA EQUIPE_CIVIL",
    "notes": "Documentos: \r\n* REGISTROS DE PROFISSIONAIS QUALIFICADOS - TECNOLOGISTA EM CONCRETO, LABORATORISTA, INSPETOR CIVIL E TOPÓGRAFO\nDocumentos:\r\n*MAPA CAMINHO DATA BOOK C&M - TUBULAÇÃO",
    "rowNumber": 92,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "INSPEÇÃO DE RECEBIMENTO - RIR_TUBULAÇÃO",
    "databook": "UHDT-D|DATA BOOK C&M|TUBULAÇÃO|RIR TUBULAÇÃO",
    "notes": "",
    "rowNumber": 96,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "INSPEÇÃO DE RECEBIMENTO DE TUBULAÇÃO - RIR",
    "databook": "UHDT-D|DATA BOOK C&M|TUBULAÇÃO|RIR TUBULAÇÃO|TUB E STH",
    "notes": "*RIR e INSPEÇÃO DE RECEBIMENTO DE PMI DE LINHAS E ELEMENTOS DE TUBULAÇÃO EM GERAL, EDCETO VÁLVULAS QUE TEM UMA SUBPASTA EDCLUSIVA",
    "rowNumber": 97,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "INSPEÇÃO DE RECEBIMENTO DE VÁLVULAS - RIR",
    "databook": "UHDT-D|DATA BOOK C&M|TUBULAÇÃO|RIR TUBULAÇÃO|VÁLVULAS",
    "notes": "*RIR e INSPEÇÃO DE RECEBIMENTO DE PMI DE VÁLVULAS",
    "rowNumber": 99,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "QUALIFICAÇÃO DA EQUIPE_TUBULAÇÃO",
    "databook": "UHDT-D|DATA BOOK C&M|TUBULAÇÃO|QUALIFICAÇÃO DA EQUIPE_TUB",
    "notes": "Documentos: \r\n*MAPA DE DOCUMENTOS.\r\n* TODA DOCUMENTAÇÃO INERENTE A QUALIFICAÇÃO DE PESSOAL DA EQUIPE DE TUBULAÇÃO.",
    "rowNumber": 101,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "END_ENSAIOS NÃO DESTRUTIVOS",
    "databook": "UHDT-D|DATA BOOK C&M|TUBULAÇÃO|END_ENSAIOS NÃO DESTRUTIVOS",
    "notes": "Documentos: \r\n*REGISTRO DE QUALIFICAÇÃO DE PESSOAL DE ENSAIOS NÃO DESTRUTIVOS (Migrar para pasta QUALIFICAÇÃO DA EQUIPE_TUBULAÇÃO)\r\n*PROCEDIMENTOS DE END \r\n*REGISTROS DE QUALIFICAÇÃO DE PROCEDIMENTO DE END; \r\n*RELATÓRIOS DE ENSAIOS NÃO-DESTRUTIVOS (ULTRASSOM, LÍQUIDO PENETRANTE, PARTÍCULAS MAGNÉTICAS, EDAMES RADIOGRÁFICOS, ETC.) \r\n* OUTROS, CONFORME NECESSIDADES DO PROJETO",
    "rowNumber": 103,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "SOLDAGEM",
    "databook": "UHDT-D|DATA BOOK C&M|TUBULAÇÃO|SOLDAGEM",
    "notes": "Documentos: \r\n*REGISTROS DE QUALIFICAÇÃO DE PROCEDIMENTO DE SOLDAGEM – (RQPS) \r\n*ESPECIFICAÇÕES DE PROCEDIMENTO DE SOLDAGEM  (EPS) \r\n*INSTRUÇÕES DE EDECUÇÃO E INSPEÇÃO DE SOLDAGEM (IEIS) \r\n*REGISTRO DE QUALIFICAÇÃO DE PROCEDIMENTO DE SOLDAGEM\r\n*REGISTROS DE ACOMPANHAMENTO DE QUALIFICAÇÃO DE SOLDADOR – (RAQS) \r\n*REGISTROS DE QUALIFICAÇÃO DE SOLDADORES E OPERADORES DE SOLDAGEM – (RQS) / ORDEM DO SINETE \r\n*LISTA DE INSPETORES QUALIFICADOS *DOCUMENTAÇÃO DOS INSPETORES (CURRÍCULOS, ACUIDADE VISUAL E CERTIFICADOS) \r\n*CERTIFICADOS DE CONSUMÍVEIS DE SOLDAGEM \r\n*MAPAS DE JUNTAS SOLDADAS - ISOMÉTRICOS SPULETADOS.\r\n*LISTA DE REGISTRO DE SOLDADORES/ OPERADORES DE SOLDAGEM QUALIFICADOS - POR SINETE (Migrar para pasta QUALIFICAÇÃO DA EQUIPE_TUBULAÇÃO) \r\n*PLANOS DE INSPEÇÃO DE SOLDAGEM_PASTA 7.3 \r\n*OUTROS, CONFORME NECESSIDADES DO PROJETO",
    "rowNumber": 105,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "CONTROLTUB",
    "databook": "UHDT-D|DATA BOOK C&M|TUBULAÇÃO|CONTROLTUB",
    "notes": "Documentos: \r\n*RELATÓRIO DE VISUAL DE AJUSTE; \r\n*RELATÓRIO DE VISUAL DE SOLDA; \r\n*RELATÓRIO DE LÍQUIDO PENETRANTE/PARTÍCULA MAGNÉTICA; \r\n*RELATÓRIO DE US/RD *RELATÓRIO DE TRATAMENTO TÉRMICO; \r\n*RELATÓRIO DE DUREZA; *RELATÓRIO DE INSPEÇÃO DE PINTURA; \r\n*RELATÓRIO DE INSPEÇÃO DE REVESTIMENTO;\r\n*RELATÓRIO DE ANÁLISES QUÍMICAS (TESTE POR PONTOS); \r\n*RELATÓRIO DE INSPEÇÃO TOPOGRÁFICA; \r\n*RELATÓRIO DE VERIFICAÇÃO DE FERRITA EM SOLDA (APLICÁVEL SOMENTE PARA SPEC L2)\"; \r\n*CERTIFICADOS DE TESTES DE PRESSÃO DE TUBULAÇÃO *RELATÓRIO DE LAVAGEM DE LINHA; *RELATÓRIO DE REMONTAGEM DE VÁLVULA; \r\n* SGS; \r\n* SGJ;\r\n* STH;\r\n* MAPA DE RASTREABILIDADE DE TUBULAÇÃO - JUNTAS E SPOOLS (EDtrato)",
    "rowNumber": 108,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M DE VÁLVULAS",
    "databook": "UHDT-D|DATA BOOK C&M|TUBULAÇÃO|C&M VÁLVULAS",
    "notes": "* MAPA DE RASTREABILIDADE DE VÁLVULAS (Nº DE * SÉRIE, DADOS DO ATUADOR / POSICIONADOR, ETC);\r\n* PLANOS DE INSPEÇÃO E TESTES - PIT\r\n* RELATÓRIOS DE INSPEÇÃO VISUAL / DIMENSIONAL;\r\n* RELATÓRIOS DE TESTES HIDROSTÁTICOS / ENSAIOS DE RECALQUE;\r\n* RELATÓRIOS DE ENSAIOS DE BANCADA (HIDROSTÁTICO / ESTANQUIDADE);\r\n* RELATÓRIOS DE CALIBRAÇÃO (VÁLVULAS DE SEGURANÇA);\r\n* RELATÓRIOS DE ENSAIOS NÃO-DESTRUTIVOS (ULTRASSOM, LÍQUIDO PENETRANTE, PARTÍCULAS MAGNÉTICAS, EDAMES RADIOGRÁFICOS, ETC.);\r\n* OUTROS RELATÓRIOS (MEDIÇÃO DE FERRITA, RELATÓRIO DE IDENTIFICAÇÃO DO MATERIAL - PMI);\r\n* RELATÓRIO DE REPARO DE VÁLVULAS (REP);\r\n* RELATÓRIO DE VERIFICAÇÃO DE VÁLVULAS (RIVVT);\r\n* OUTROS, CONFORME NECESSIDADES DO PROJETO",
    "rowNumber": 110,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M DE TUBULAÇÃO",
    "databook": "UHDT-D|DATA BOOK C&M|TUBULAÇÃO|C&M TUBULAÇÃO",
    "notes": "* RELATÓRIOS DE INSPEÇÃO VISUAL / DIMENSIONAL;\r\n* RELATORIO DE FLUSHING;\r\n* RELATÓRIOS DE INSTALAÇÃO DE ISOLAMENTOS TÉRMICOS / FIRE-PROOF;\r\n* RELATÓRIO DE METALIZAÇÃO\r\n* RELATÓRIO DE GALVANIZAÇÃO",
    "rowNumber": 112,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "TESTES FUNCIONAIS_TUBULAÇÃO",
    "databook": "UHDT-D|DATA BOOK C&M|TUBULAÇÃO|TESTES FUNCIONAIS",
    "notes": "* CERTIFICADO DE MONTAGEM DO SISTEMA\r\n* REMONTAGEM\r\n* SOPRAGEM\r\n* LAVAGEM DE LINHA\r\n* LIMPEZA QUÍMICA\r\n* LEAK TEST\r\n* SUPORTE DE TUBULAÇÃO\r\n* RELATÓRIOS DE TESTES HIDROSTÁTICOS / ESTANQUIDADE",
    "rowNumber": 114,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PRONTUÁRIOS NR13_SPIE - ISOCORROSIVOS",
    "databook": "UHDT-D|DATA BOOK C&M|TUBULAÇÃO|PRONT. NR13_SPIE - ISOCORROSIVOS",
    "notes": "Documentos: \r\n* RELATÓRIO DE INSPEÇÃO EDTERNA/ INTERNA (RISI.EDT.INT.SPIE)\r\n* RELATÓRIOS DE ME (US-ME.SPIE); \r\n* RELATÓRIO DE IDENTIFICAÇÃO POSITIVA DE MATERIAL;\r\n* RELATÓRIOS DE PMI PÓS MONTAGEM (PMI.SPIE);\r\n* PROJETO DE ALTERAÇÃO E REPARO (PAR.SPIE);\r\n* RELATÓRIO DE MEDIÇÃO DE ESPESSURA + ANÁLISE DE VIDA RESIDUAL (US-ME.SPIE);\r\n* CERTIFICADO DE CALIBRAÇÃO DE SUPORTE DE MOLA (SUP.MOLA.SPIE );\r\n* FLUDOGRA DE INSPEÇÃO DE ISOCORROSIVOS (FLUDOG.SPIE)\nDocumentos:\r\n*MAPA CAMINHO DATA BOOK C&M - EQP DINÂMICOS",
    "rowNumber": 116,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "INSPEÇÃO DE RECEBIMENTO - RIR_DINÂMICOS",
    "databook": "UHDT-D|DATA BOOK C&M|EQP DINÂMICOS|RIR",
    "notes": "Documentos:\r\n*MAPA RIRs",
    "rowNumber": 120,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR BOMBA",
    "databook": "UHDT-D|DATA BOOK C&M|EQP DINÂMICOS|RIR|BOMBA",
    "notes": "Documentos:\r\n*RIR",
    "rowNumber": 122,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR COMPRESSOR",
    "databook": "UHDT-D|DATA BOOK C&M|EQP DINÂMICOS|RIR|COMPRESSOR",
    "notes": "Documentos:\r\n*RIR",
    "rowNumber": 124,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR TURBINAS",
    "databook": "UHDT-D|DATA BOOK C&M|EQP DINÂMICOS|RIR|TURBINA",
    "notes": "Documentos:\r\n*RIR",
    "rowNumber": 126,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR PONTE ROLANTE",
    "databook": "UHDT-D|DATA BOOK C&M|EQP DINÂMICOS|RIR|PONTE ROLANTE",
    "notes": "Documentos:\r\n*RIR",
    "rowNumber": 128,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR UNIDADE DE LUBRIFICAÇÃO",
    "databook": "UHDT-D|DATA BOOK C&M|EQP DINÂMICOS|RIR|UNIDADE DE LUBRIFICAÇÃO",
    "notes": "Documentos:\r\n*RIR",
    "rowNumber": 130,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR VENTILADOR",
    "databook": "UHDT-D|DATA BOOK C&M|EQP DINÂMICOS|RIR|VENTILADOR",
    "notes": "Documentos:\r\n*RIR",
    "rowNumber": 132,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR DEMAIS EQP DINÂMICOS",
    "databook": "UHDT-D|DATA BOOK C&M|EQP DINÂMICOS|RIR|DEMAIS EQP DINÂMICOS",
    "notes": "Documentos:\r\n*RIR",
    "rowNumber": 134,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PLANOS DE INSPEÇÃO E TESTES - PIT_DINÂMICOS",
    "databook": "UHDT-D|DATA BOOK C&M|EQP DINÂMICOS|PLANO DE INSPEÇÃO E TESTES - PIT",
    "notes": "Documentos:\r\n* INSPEÇÃO E TESTE - PIT.",
    "rowNumber": 136,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M - BOMBA",
    "databook": "UHDT-D|DATA BOOK C&M|EQP DINÂMICOS|C&M - BOMBA",
    "notes": "Documentos:\r\nDocumentos:\r\n* RELATÓRIOS DE CONSTRUÇÃO / INSPEÇÃO DAS BASES;\r\n* RELATÓRIOS DE BALANCEAMENTO DO CONJUNTO ROTATIVO;\r\n* RELATÓRIOS DE C&M (PRÉ-ALINHAMENTO / ALINHAMENTO APÓS GRAUTEAMENTO / NIVELAMENTO);\r\n* RELATÓRIOS DE ALINHAMENTO FINAL;\r\n* RELATÓRIOS DE INSTALAÇÃO DE ISOLAMENTOS TÉRMICOS / FIRE-PROOF.\r\n* RELATÓRIOS DE TORQUEAMENTO",
    "rowNumber": 138,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M - COMPRESSOR",
    "databook": "UHDT-D|DATA BOOK C&M|EQP DINÂMICOS|C&M - COMPRESSOR",
    "notes": "Documentos:\r\nDocumentos:\r\n* RELATÓRIOS DE CONSTRUÇÃO / INSPEÇÃO DAS BASES;\r\n* RELATÓRIOS DE BALANCEAMENTO DO CONJUNTO ROTATIVO;\r\n* RELATÓRIOS DE C&M (PRÉ-ALINHAMENTO / ALINHAMENTO APÓS GRAUTEAMENTO / NIVELAMENTO);\r\n* RELATÓRIOS DE ALINHAMENTO FINAL;\r\n* RELATÓRIOS DE INSTALAÇÃO DE ISOLAMENTOS TÉRMICOS / FIRE-PROOF.\r\n* RELATÓRIOS DE TORQUEAMENTO",
    "rowNumber": 140,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M - TURBINA",
    "databook": "UHDT-D|DATA BOOK C&M|EQP DINÂMICOS|C&M - TURBINA",
    "notes": "Documentos:\r\nDocumentos:\r\n* RELATÓRIOS DE CONSTRUÇÃO / INSPEÇÃO DAS BASES;\r\n* RELATÓRIOS DE BALANCEAMENTO DO CONJUNTO ROTATIVO;\r\n* RELATÓRIOS DE MONTAGEM (PRÉ-ALINHAMENTO / ALINHAMENTO APÓS GRAUTEAMENTO / NIVELAMENTO);\r\n* RELATÓRIOS DE ALINHAMENTO FINAL;\r\n* RELATÓRIOS DE INSTALAÇÃO DE ISOLAMENTOS TÉRMICOS / FIRE-PROOF.\r\n* RELATÓRIOS DE TORQUEAMENTO",
    "rowNumber": 142,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M - PONTE ROLANTE",
    "databook": "UHDT-D|DATA BOOK C&M|EQP DINÂMICOS|C&M - PONTE ROLANTE",
    "notes": "Documentos:\r\nDocumentos:\r\n* RELATÓRIOS DE CONSTRUÇÃO / INSPEÇÃO DAS BASES;\r\n* RELATÓRIOS DE BALANCEAMENTO DO CONJUNTO ROTATIVO;\r\n* RELATÓRIOS DE MONTAGEM (PRÉ-ALINHAMENTO / ALINHAMENTO APÓS GRAUTEAMENTO / NIVELAMENTO);\r\n* RELATÓRIOS DE ALINHAMENTO FINAL;\r\n* RELATÓRIOS DE INSTALAÇÃO DE ISOLAMENTOS TÉRMICOS / FIRE-PROOF.\r\n* RELATÓRIOS DE TORQUEAMENTO",
    "rowNumber": 144,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M - UNIDADE DE LUBRIFICAÇÃO",
    "databook": "UHDT-D|DATA BOOK C&M|EQP DINÂMICOS|C&M - UNIDADE DE LUBRIFICAÇÃO",
    "notes": "Documentos:\r\nDocumentos:\r\n* RELATÓRIOS DE CONSTRUÇÃO / INSPEÇÃO DAS BASES;\r\n* RELATÓRIOS DE BALANCEAMENTO DO CONJUNTO ROTATIVO;\r\n* RELATÓRIOS DE MONTAGEM (PRÉ-ALINHAMENTO / ALINHAMENTO APÓS GRAUTEAMENTO / NIVELAMENTO);\r\n* RELATÓRIOS DE ALINHAMENTO FINAL;\r\n* RELATÓRIOS DE INSTALAÇÃO DE ISOLAMENTOS TÉRMICOS / FIRE-PROOF.\r\n* RELATÓRIOS DE TORQUEAMENTO",
    "rowNumber": 146,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M -VENTILADOR",
    "databook": "UHDT-D|DATA BOOK C&M|EQP DINÂMICOS|C&M - VENTILADOR",
    "notes": "Documentos:\r\nDocumentos:\r\n* RELATÓRIOS DE CONSTRUÇÃO / INSPEÇÃO DAS BASES;\r\n* RELATÓRIOS DE BALANCEAMENTO DO CONJUNTO ROTATIVO;\r\n* RELATÓRIOS DE MONTAGEM (PRÉ-ALINHAMENTO / ALINHAMENTO APÓS GRAUTEAMENTO / NIVELAMENTO);\r\n* RELATÓRIOS DE ALINHAMENTO FINAL;\r\n* RELATÓRIOS DE INSTALAÇÃO DE ISOLAMENTOS TÉRMICOS / FIRE-PROOF.\r\n* RELATÓRIOS DE TORQUEAMENTO",
    "rowNumber": 148,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M - DEMAIS EQP DINÂMICOS",
    "databook": "UHDT-D|DATA BOOK C&M|EQP DINÂMICOS|C&M - DEMAIS EQP DINÂMICOS",
    "notes": "Documentos:\r\nDocumentos:\r\n* RELATÓRIOS DE CONSTRUÇÃO / INSPEÇÃO DAS BASES;\r\n* RELATÓRIOS DE BALANCEAMENTO DO CONJUNTO ROTATIVO;\r\n* RELATÓRIOS DE MONTAGEM (PRÉ-ALINHAMENTO / ALINHAMENTO APÓS GRAUTEAMENTO / NIVELAMENTO);\r\n* RELATÓRIOS DE ALINHAMENTO FINAL;\r\n* RELATÓRIOS DE INSTALAÇÃO DE ISOLAMENTOS TÉRMICOS / FIRE-PROOF.\r\n* RELATÓRIOS DE TORQUEAMENTO",
    "rowNumber": 150,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RELATÓRIOS DE TESTE FUNCIONAIS",
    "databook": "UHDT-D|DATA BOOK C&M|EQP DINÂMICOS|TESTES FUNCIONAIS",
    "notes": "Documentos:\r\n*RELATÓRIOS DE TESTES FUNCIONAIS (REGISTROS DE NÍVEL DE RUÍDO, VIBRAÇÃO, ETC.);\r\n* RELATÓRIOS DE TESTE DE ADERÊNCIA.\r\n* CERTIFICADO DE CONDICIONAMENTO DAS LINHAS ASSOCIADAS (LIMPEZA QUÍMICA / PASSIVAÇÃO / FLUSHING / TESTES HIDROSTÁTICOS / ETC.);\r\n* RELATÓRIO DE FLUSH.",
    "rowNumber": 152,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "SISTEMAS AUDILIARES",
    "databook": "UHDT-D|DATA BOOK C&M|EQP DINÂMICOS|INTERLIGAÇÕES DE SISTEMAS AUDILIARES",
    "notes": "Documentos:\r\n* RELATÓRIOS DE TUBULAÇÕES (PARALELISMO / ALINHAMENTO / CONCENTRICIDADE E AFASTAMENTO ENTRE FLANGES)\nDocumentos:\r\n*MAPA CAMINHO DATA BOOK C&M - EQP DE SEGURANÇA",
    "rowNumber": 154,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "INSPEÇÃO DE RECEBIMENTO - RIR_EQP. SEGURANÇA",
    "databook": "UHDT-D|DATA BOOK C&M|EQP SEGURANÇA|RIR EQP_SEGURANÇA",
    "notes": "Documentos:\r\n* TODAS AS RIRs DE SEGURANÇA",
    "rowNumber": 158,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PLANOS DE INSPEÇÃO E TESTES - PIT_EQP SEGURANÇA",
    "databook": "UHDT-D|DATA BOOK C&M|EQP SEGURANÇA|PLANO  DE INSPEÇÃO E TESTES - PIT",
    "notes": "Documentos:\r\n* INSPEÇÃO E TESTE - PIT.",
    "rowNumber": 160,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "INSPEÇÃO VISUAIS, ENSAIOS E TESTES_EQP SEGURANÇA",
    "databook": "UHDT-D|DATA BOOK C&M|EQP SEGURANÇA|INSPEÇÃO VISUAIS, ENSAIOS E TESTES",
    "notes": "Documentos:\r\n* INSPEÇÃO VISUAL.\r\n* RELATÓRIOS DE TESTE FUNCIONAIS;\r\n* DEMAIS RELATÓRIOS.",
    "rowNumber": 162,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M_EQP SEGURANÇA",
    "databook": "UHDT-D|DATA BOOK C&M|EQP SEGURANÇA|C&M_EQP. SEGURANÇA",
    "notes": "Documentos:\r\n* RELATÓRIOS DE INSTALAÇÃO/ MONTAGEM\r\n* RELATÓRIOS DE ALINHAMENTO FINAL;\r\n* CERTIFICADOS DE INSTITORES\nDocumentos:\r\n*MAPA CAMINHO DATA BOOK C&M - EQP ESTÁTICOS",
    "rowNumber": 164,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "INSPEÇÃO DE RECEBIMENTO - RIR_ESTÁTICO",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICOS|RIR",
    "notes": "",
    "rowNumber": 168,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR FORNO",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICO|RIR|FORNO",
    "notes": "Documentos:\r\n* Todas as RIRs",
    "rowNumber": 169,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR REATOR",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICO|RIR|REATOR",
    "notes": "Documentos:\r\n* Todas as RIRs",
    "rowNumber": 171,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR VASOS E TANQUES",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICO|RIR|VASOS E TANQUES",
    "notes": "Documentos:\r\n* Todas as RIRs",
    "rowNumber": 173,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR PERMUTADORES E TROCADORES DE CALOR",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICO|RIR|PERMUTADORES E TROCADORES DE CALOR",
    "notes": "Documentos:\r\n* Todas as RIRs",
    "rowNumber": 175,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR TORRE",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICO|RIR|TORRE",
    "notes": "Documentos:\r\n* Todas as RIRs",
    "rowNumber": 177,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR DEMAIS EQP ESTÁTICOS",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICO|RIR|EQP ESTÁTICOS DIVERSOS",
    "notes": "Documentos:\r\n* Todas as RIRs",
    "rowNumber": 179,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR UNIDADES MODULADAS",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICO|RIR|EQP ESTÁTICOS UNIDADES MODULADAS",
    "notes": "Documentos:\r\n* Todas as RIRs",
    "rowNumber": 181,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M - FORNO",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICOS|C&M FORNO",
    "notes": "Documentos:\r\n* RELATÓRIOS DE LOCAÇÃO,  NIVELAMENTO / VERTICALIZAÇÃO;\r\n* RELATÓRIOS DE ASSENTAMENTO E NIVELAMENTO TOPOGRÁFICO DE CALÇOS E BASES;\r\n* RELATÓRIOS DE MONTAGEM DE EQUIPAMENTOS (INCLUINDO INTERNOS);\r\n* RELATÓRIOS DE TUBULAÇÕES (PARALELISMO / ALINHAMENTO / CONCENTRICIDADE E AFASTAMENTO ENTRE FLANGES);\r\n* RELATÓRIOS DE TORQUEAMENTO;\r\n* RELATÓRIOS DE INSTALAÇÃO DE ISOLAMENTOS TÉRMICOS / FIRE-PROOF;\r\n* RELATÓRIOS DE INSTALAÇÃO DE REFRATÁRIOS;\r\n* OUTROS, CONFORME NECESSIDADES DO PROJETO.\r\n* RELATÓRIOS DE INSTALAÇÃO DE REFRATÁRIOS;",
    "rowNumber": 183,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M - REATOR",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICOS|C&M REATOR",
    "notes": "Documentos:\r\n* RELATÓRIOS DE LOCAÇÃO,  NIVELAMENTO / VERTICALIZAÇÃO;\r\n* RELATÓRIOS DE ASSENTAMENTO E NIVELAMENTO TOPOGRÁFICO DE CALÇOS E BASES;\r\n* RELATÓRIOS DE MONTAGEM DE EQUIPAMENTOS (INCLUINDO INTERNOS);\r\n* RELATÓRIOS DE TUBULAÇÕES (PARALELISMO / ALINHAMENTO / CONCENTRICIDADE E AFASTAMENTO ENTRE FLANGES);\r\n* RELATÓRIOS DE TORQUEAMENTO;\r\n* RELATÓRIOS DE INSTALAÇÃO DE ISOLAMENTOS TÉRMICOS / FIRE-PROOF;\r\n* RELATÓRIOS DE INSTALAÇÃO DE REFRATÁRIOS;\r\n* OUTROS, CONFORME NECESSIDADES DO PROJETO.\r\n* RELATÓRIOS DE INSTALAÇÃO DE REFRATÁRIOS;",
    "rowNumber": 185,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M - VASOS E TANQUES",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICOS|C&M VASOS E TANQUES",
    "notes": "Documentos:\r\n* RELATÓRIOS DE LOCAÇÃO,  NIVELAMENTO / VERTICALIZAÇÃO;\r\n* RELATÓRIOS DE ASSENTAMENTO E NIVELAMENTO TOPOGRÁFICO DE CALÇOS E BASES;\r\n* RELATÓRIOS DE MONTAGEM DE EQUIPAMENTOS (INCLUINDO INTERNOS);\r\n* RELATÓRIOS DE TUBULAÇÕES (PARALELISMO / ALINHAMENTO / CONCENTRICIDADE E AFASTAMENTO ENTRE FLANGES);\r\n* RELATÓRIOS DE TORQUEAMENTO;\r\n* RELATÓRIOS DE INSTALAÇÃO DE ISOLAMENTOS TÉRMICOS / FIRE-PROOF;\r\n* RELATÓRIOS DE INSTALAÇÃO DE REFRATÁRIOS;\r\n* OUTROS, CONFORME NECESSIDADES DO PROJETO.\r\n* RELATÓRIOS DE INSTALAÇÃO DE REFRATÁRIOS;",
    "rowNumber": 187,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M - PERMUTADORES E TROCADORES DE CALOR",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICOS|C&M PERMUTADORES E TROCADORES DE CALOR",
    "notes": "Documentos:\r\n* RELATÓRIOS DE LOCAÇÃO,  NIVELAMENTO / VERTICALIZAÇÃO;\r\n* RELATÓRIOS DE ASSENTAMENTO E NIVELAMENTO TOPOGRÁFICO DE CALÇOS E BASES;\r\n* RELATÓRIOS DE MONTAGEM DE EQUIPAMENTOS (INCLUINDO INTERNOS);\r\n* RELATÓRIOS DE TUBULAÇÕES (PARALELISMO / ALINHAMENTO / CONCENTRICIDADE E AFASTAMENTO ENTRE FLANGES);\r\n* RELATÓRIOS DE TORQUEAMENTO;\r\n* RELATÓRIOS DE INSTALAÇÃO DE ISOLAMENTOS TÉRMICOS / FIRE-PROOF;\r\n* RELATÓRIOS DE INSTALAÇÃO DE REFRATÁRIOS;\r\n* OUTROS, CONFORME NECESSIDADES DO PROJETO.\r\n* RELATÓRIOS DE INSTALAÇÃO DE REFRATÁRIOS;",
    "rowNumber": 189,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M - TORRES",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICOS|C&M TORRES",
    "notes": "Documentos:\r\n* RELATÓRIOS DE LOCAÇÃO,  NIVELAMENTO / VERTICALIZAÇÃO;\r\n* RELATÓRIOS DE ASSENTAMENTO E NIVELAMENTO TOPOGRÁFICO DE CALÇOS E BASES;\r\n* RELATÓRIOS DE MONTAGEM DE EQUIPAMENTOS (INCLUINDO INTERNOS);\r\n* RELATÓRIOS DE TUBULAÇÕES (PARALELISMO / ALINHAMENTO / CONCENTRICIDADE E AFASTAMENTO ENTRE FLANGES);\r\n* RELATÓRIOS DE TORQUEAMENTO;\r\n* RELATÓRIOS DE INSTALAÇÃO DE ISOLAMENTOS TÉRMICOS / FIRE-PROOF;\r\n* RELATÓRIOS DE INSTALAÇÃO DE REFRATÁRIOS;\r\n* OUTROS, CONFORME NECESSIDADES DO PROJETO.\r\n* RELATÓRIOS DE INSTALAÇÃO DE REFRATÁRIOS;",
    "rowNumber": 191,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M - DEMAIS EQUIPAMENTOS",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICOS|C&M DEMAIS EQP ESTÁTICOS",
    "notes": "Documentos:\r\n* RELATÓRIOS DE LOCAÇÃO,  NIVELAMENTO / VERTICALIZAÇÃO;\r\n* RELATÓRIOS DE ASSENTAMENTO E NIVELAMENTO TOPOGRÁFICO DE CALÇOS E BASES;\r\n* RELATÓRIOS DE MONTAGEM DE EQUIPAMENTOS (INCLUINDO INTERNOS);\r\n* RELATÓRIOS DE TUBULAÇÕES (PARALELISMO / ALINHAMENTO / CONCENTRICIDADE E AFASTAMENTO ENTRE FLANGES);\r\n* RELATÓRIOS DE TORQUEAMENTO;\r\n* RELATÓRIOS DE INSTALAÇÃO DE ISOLAMENTOS TÉRMICOS / FIRE-PROOF;\r\n* RELATÓRIOS DE INSTALAÇÃO DE REFRATÁRIOS;\r\n* OUTROS, CONFORME NECESSIDADES DO PROJETO.\r\n* RELATÓRIOS DE INSTALAÇÃO DE REFRATÁRIOS;",
    "rowNumber": 193,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M - UNIDADES MODULARES",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICOS|C&M UNIDADES MODULARES",
    "notes": "Documentos:\r\n* RELATÓRIOS DE LOCAÇÃO,  NIVELAMENTO / VERTICALIZAÇÃO;\r\n* RELATÓRIOS DE ASSENTAMENTO E NIVELAMENTO TOPOGRÁFICO DE CALÇOS E BASES;\r\n* RELATÓRIOS DE MONTAGEM DE EQUIPAMENTOS (INCLUINDO INTERNOS);\r\n* RELATÓRIOS DE TUBULAÇÕES (PARALELISMO / ALINHAMENTO / CONCENTRICIDADE E AFASTAMENTO ENTRE FLANGES);\r\n* RELATÓRIOS DE TORQUEAMENTO;\r\n* RELATÓRIOS DE INSTALAÇÃO DE ISOLAMENTOS TÉRMICOS / FIRE-PROOF;\r\n* RELATÓRIOS DE INSTALAÇÃO DE REFRATÁRIOS;\r\n* OUTROS, CONFORME NECESSIDADES DO PROJETO.\r\n* RELATÓRIOS DE INSTALAÇÃO DE REFRATÁRIOS;",
    "rowNumber": 195,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "INSPEÇÕES VISUAIS, TESTES E ENSAIOS",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICOS|INSPEÇÃO VISUAIS, TESTES E ENSAIOS INICIAIS",
    "notes": "",
    "rowNumber": 197,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "INSPEÇÃO VISUAIS, TESTES E ENSAIOS_FORNO",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICO|INSPEÇÃO VISUAIS, TESTES E ENSAIOS INICIAIS|FORNO",
    "notes": "Documentos:\r\n* PLANOS DE INSPEÇÃO E TESTES - PIT;\r\n* RELATÓRIOS DE INSPEÇÃO VISUAL / DIMENSIONAL;\r\n* RELATÓRIOS DE BOROSCOPIA (BOR);\r\n* RELATÓRIOS DE IDENTIFICAÇÃO DE MATERIAL (PMI);\r\n* RELATÓRIOS DE IRIS (IRIS);\r\n* RELATÓRIOS DE ENSAIOS NÃO-DESTRUTIVOS (ULTRASSOM, LÍQUIDO PENETRANTE, PARTÍCULAS MAGNÉTICAS, ENSAIOS RADIOGRÁFICOS, ETC.);\r\n* RELATÓRIOS DE INSPEÇÃO DE LOCAÇÃO DE EQUIPAMENTOS ESTÁTICOS (COORDENADAS / ALINHAMENTO E NÍVEL);\r\n* RELATÓRIOS DE TRATAMENTO TÉRMICO E TESTE DE DUREZA;\r\n* OUTROS RELATÓRIOS (MEDIÇÃO DE FERRITA, RELATÓRIO DE IDENTIFICAÇÃO DO MATERIAL - PMI);\r\n* RELATÓRIOS DE TESTES DE ESTANQUEIDADE;\r\n* RELATÓRIOS DE TESTES HIDROSTÁTICOS / ENSAIOS DE RECALQUE;\r\n* RELATÓRIOS DE ENSAIOS DE RECALQUE;\r\n* RELATÓRIOS DE TESTES DE ESTANQUEIDADE (CTEE);\r\n* RELATÓRIOS DE TESTES HIDROSTÁTICOS (CTPE);\r\n* RELATÓRIOS DE TRATAMENTO TÉRMICO E TESTE DE DUREZA.",
    "rowNumber": 198,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "INSPEÇÃO VISUAIS, TESTES E ENSAIOS_REATOR",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICO|INSPEÇÃO VISUAIS, TESTES E ENSAIOS INICIAIS|REATOR",
    "notes": "Documentos:\r\n* PLANOS DE INSPEÇÃO E TESTES - PIT;\r\n* RELATÓRIOS DE INSPEÇÃO VISUAL / DIMENSIONAL;\r\n* RELATÓRIOS DE BOROSCOPIA (BOR);\r\n* RELATÓRIOS DE IDENTIFICAÇÃO DE MATERIAL (PMI);\r\n* RELATÓRIOS DE IRIS (IRIS);\r\n* RELATÓRIOS DE ENSAIOS NÃO-DESTRUTIVOS (ULTRASSOM, LÍQUIDO PENETRANTE, PARTÍCULAS MAGNÉTICAS, ENSAIOS RADIOGRÁFICOS, ETC.);\r\n* RELATÓRIOS DE INSPEÇÃO DE LOCAÇÃO DE EQUIPAMENTOS ESTÁTICOS (COORDENADAS / ALINHAMENTO E NÍVEL);\r\n* RELATÓRIOS DE TRATAMENTO TÉRMICO E TESTE DE DUREZA;\r\n* OUTROS RELATÓRIOS (MEDIÇÃO DE FERRITA, RELATÓRIO DE IDENTIFICAÇÃO DO MATERIAL - PMI);\r\n* RELATÓRIOS DE TESTES DE ESTANQUEIDADE;\r\n* RELATÓRIOS DE TESTES HIDROSTÁTICOS / ENSAIOS DE RECALQUE;\r\n* RELATÓRIOS DE ENSAIOS DE RECALQUE;\r\n* RELATÓRIOS DE TESTES DE ESTANQUEIDADE (CTEE);\r\n* RELATÓRIOS DE TESTES HIDROSTÁTICOS (CTPE);\r\n* RELATÓRIOS DE TRATAMENTO TÉRMICO E TESTE DE DUREZA.",
    "rowNumber": 200,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "INSPEÇÃO VISUAIS, TESTES E ENSAIOS_VASOS E TANQUES",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICO|INSPEÇÃO VISUAIS, TESTES E ENSAIOS INICIAIS|VASOS E TANQUES",
    "notes": "Documentos:\r\n* PLANOS DE INSPEÇÃO E TESTES - PIT;\r\n* RELATÓRIOS DE INSPEÇÃO VISUAL / DIMENSIONAL;\r\n* RELATÓRIOS DE BOROSCOPIA (BOR);\r\n* RELATÓRIOS DE IDENTIFICAÇÃO DE MATERIAL (PMI);\r\n* RELATÓRIOS DE IRIS (IRIS);\r\n* RELATÓRIOS DE ENSAIOS NÃO-DESTRUTIVOS (ULTRASSOM, LÍQUIDO PENETRANTE, PARTÍCULAS MAGNÉTICAS, ENSAIOS RADIOGRÁFICOS, ETC.);\r\n* RELATÓRIOS DE INSPEÇÃO DE LOCAÇÃO DE EQUIPAMENTOS ESTÁTICOS (COORDENADAS / ALINHAMENTO E NÍVEL);\r\n* RELATÓRIOS DE TRATAMENTO TÉRMICO E TESTE DE DUREZA;\r\n* OUTROS RELATÓRIOS (MEDIÇÃO DE FERRITA, RELATÓRIO DE IDENTIFICAÇÃO DO MATERIAL - PMI);\r\n* RELATÓRIOS DE TESTES DE ESTANQUEIDADE;\r\n* RELATÓRIOS DE TESTES HIDROSTÁTICOS / ENSAIOS DE RECALQUE;\r\n* RELATÓRIOS DE ENSAIOS DE RECALQUE;\r\n* RELATÓRIOS DE TESTES DE ESTANQUEIDADE (CTEE);\r\n* RELATÓRIOS DE TESTES HIDROSTÁTICOS (CTPE);\r\n* RELATÓRIOS DE TRATAMENTO TÉRMICO E TESTE DE DUREZA.",
    "rowNumber": 202,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "INSPEÇÃO VISUAIS, TESTES E ENSAIOS_TROCADOR DE CALOR",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICO|INSPEÇÃO VISUAIS, TESTES E ENSAIOS INICIAIS|TROCADOR DE CALOR",
    "notes": "Documentos:\r\n* PLANOS DE INSPEÇÃO E TESTES - PIT;\r\n* RELATÓRIOS DE INSPEÇÃO VISUAL / DIMENSIONAL;\r\n* RELATÓRIOS DE BOROSCOPIA (BOR);\r\n* RELATÓRIOS DE IDENTIFICAÇÃO DE MATERIAL (PMI);\r\n* RELATÓRIOS DE IRIS (IRIS);\r\n* RELATÓRIOS DE ENSAIOS NÃO-DESTRUTIVOS (ULTRASSOM, LÍQUIDO PENETRANTE, PARTÍCULAS MAGNÉTICAS, ENSAIOS RADIOGRÁFICOS, ETC.);\r\n* RELATÓRIOS DE INSPEÇÃO DE LOCAÇÃO DE EQUIPAMENTOS ESTÁTICOS (COORDENADAS / ALINHAMENTO E NÍVEL);\r\n* RELATÓRIOS DE TRATAMENTO TÉRMICO E TESTE DE DUREZA;\r\n* OUTROS RELATÓRIOS (MEDIÇÃO DE FERRITA, RELATÓRIO DE IDENTIFICAÇÃO DO MATERIAL - PMI);\r\n* RELATÓRIOS DE TESTES DE ESTANQUEIDADE;\r\n* RELATÓRIOS DE TESTES HIDROSTÁTICOS / ENSAIOS DE RECALQUE;\r\n* RELATÓRIOS DE ENSAIOS DE RECALQUE;\r\n* RELATÓRIOS DE TESTES DE ESTANQUEIDADE (CTEE);\r\n* RELATÓRIOS DE TESTES HIDROSTÁTICOS (CTPE);\r\n* RELATÓRIOS DE TRATAMENTO TÉRMICO E TESTE DE DUREZA.",
    "rowNumber": 204,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "INSPEÇÃO VISUAIS, TESTES E ENSAIOS_TORRE",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICO|INSPEÇÃO VISUAIS, TESTES E ENSAIOS INICIAIS|TORRE",
    "notes": "Documentos:\r\n* PLANOS DE INSPEÇÃO E TESTES - PIT;\r\n* RELATÓRIOS DE INSPEÇÃO VISUAL / DIMENSIONAL;\r\n* RELATÓRIOS DE BOROSCOPIA (BOR);\r\n* RELATÓRIOS DE IDENTIFICAÇÃO DE MATERIAL (PMI);\r\n* RELATÓRIOS DE IRIS (IRIS);\r\n* RELATÓRIOS DE ENSAIOS NÃO-DESTRUTIVOS (ULTRASSOM, LÍQUIDO PENETRANTE, PARTÍCULAS MAGNÉTICAS, ENSAIOS RADIOGRÁFICOS, ETC.);\r\n* RELATÓRIOS DE INSPEÇÃO DE LOCAÇÃO DE EQUIPAMENTOS ESTÁTICOS (COORDENADAS / ALINHAMENTO E NÍVEL);\r\n* RELATÓRIOS DE TRATAMENTO TÉRMICO E TESTE DE DUREZA;\r\n* OUTROS RELATÓRIOS (MEDIÇÃO DE FERRITA, RELATÓRIO DE IDENTIFICAÇÃO DO MATERIAL - PMI);\r\n* RELATÓRIOS DE TESTES DE ESTANQUEIDADE;\r\n* RELATÓRIOS DE TESTES HIDROSTÁTICOS / ENSAIOS DE RECALQUE;\r\n* RELATÓRIOS DE ENSAIOS DE RECALQUE;\r\n* RELATÓRIOS DE TESTES DE ESTANQUEIDADE (CTEE);\r\n* RELATÓRIOS DE TESTES HIDROSTÁTICOS (CTPE);\r\n* RELATÓRIOS DE TRATAMENTO TÉRMICO E TESTE DE DUREZA.",
    "rowNumber": 206,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "INSPEÇÃO VISUAIS, TESTES E ENSAIOS_DEMAIS EQP ESTÁTICOS",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICO|INSPEÇÃO VISUAIS, TESTES E ENSAIOS INICIAIS|EQP ESTÁTICOS DIVERSOS",
    "notes": "Documentos:\r\n* PLANOS DE INSPEÇÃO E TESTES - PIT;\r\n* RELATÓRIOS DE INSPEÇÃO VISUAL / DIMENSIONAL;\r\n* RELATÓRIOS DE BOROSCOPIA (BOR);\r\n* RELATÓRIOS DE IDENTIFICAÇÃO DE MATERIAL (PMI);\r\n* RELATÓRIOS DE IRIS (IRIS);\r\n* RELATÓRIOS DE ENSAIOS NÃO-DESTRUTIVOS (ULTRASSOM, LÍQUIDO PENETRANTE, PARTÍCULAS MAGNÉTICAS, ENSAIOS RADIOGRÁFICOS, ETC.);\r\n* RELATÓRIOS DE INSPEÇÃO DE LOCAÇÃO DE EQUIPAMENTOS ESTÁTICOS (COORDENADAS / ALINHAMENTO E NÍVEL);\r\n* RELATÓRIOS DE TRATAMENTO TÉRMICO E TESTE DE DUREZA;\r\n* OUTROS RELATÓRIOS (MEDIÇÃO DE FERRITA, RELATÓRIO DE IDENTIFICAÇÃO DO MATERIAL - PMI);\r\n* RELATÓRIOS DE TESTES DE ESTANQUEIDADE;\r\n* RELATÓRIOS DE TESTES HIDROSTÁTICOS / ENSAIOS DE RECALQUE;\r\n* RELATÓRIOS DE ENSAIOS DE RECALQUE;\r\n* RELATÓRIOS DE TESTES DE ESTANQUEIDADE (CTEE);\r\n* RELATÓRIOS DE TESTES HIDROSTÁTICOS (CTPE);\r\n* RELATÓRIOS DE TRATAMENTO TÉRMICO E TESTE DE DUREZA.",
    "rowNumber": 208,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "INSPEÇÃO VISUAIS, TESTES E ENSAIOS_UNIDADES MODULARES",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICO|INSPEÇÃO VISUAIS, TESTES E ENSAIOS INICIAIS|UNIDADES MODULARES",
    "notes": "Documentos:\r\n* PLANOS DE INSPEÇÃO E TESTES - PIT;\r\n* RELATÓRIOS DE INSPEÇÃO VISUAL / DIMENSIONAL;\r\n* RELATÓRIOS DE BOROSCOPIA (BOR);\r\n* RELATÓRIOS DE IDENTIFICAÇÃO DE MATERIAL (PMI);\r\n* RELATÓRIOS DE IRIS (IRIS);\r\n* RELATÓRIOS DE ENSAIOS NÃO-DESTRUTIVOS (ULTRASSOM, LÍQUIDO PENETRANTE, PARTÍCULAS MAGNÉTICAS, ENSAIOS RADIOGRÁFICOS, ETC.);\r\n* RELATÓRIOS DE INSPEÇÃO DE LOCAÇÃO DE EQUIPAMENTOS ESTÁTICOS (COORDENADAS / ALINHAMENTO E NÍVEL);\r\n* RELATÓRIOS DE TRATAMENTO TÉRMICO E TESTE DE DUREZA;\r\n* OUTROS RELATÓRIOS (MEDIÇÃO DE FERRITA, RELATÓRIO DE IDENTIFICAÇÃO DO MATERIAL - PMI);\r\n* RELATÓRIOS DE TESTES DE ESTANQUEIDADE;\r\n* RELATÓRIOS DE TESTES HIDROSTÁTICOS / ENSAIOS DE RECALQUE;\r\n* RELATÓRIOS DE ENSAIOS DE RECALQUE;\r\n* RELATÓRIOS DE TESTES DE ESTANQUEIDADE (CTEE);\r\n* RELATÓRIOS DE TESTES HIDROSTÁTICOS (CTPE);\r\n* RELATÓRIOS DE TRATAMENTO TÉRMICO E TESTE DE DUREZA.",
    "rowNumber": 210,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "QUALIFICAÇÃO EQUIPE_ESTÁTICOS",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICOS|QUALIFICAÇÃO DA EQUIPE_EQP ESTÁTICOSS",
    "notes": "Documentos:\r\n* REGISTRO DE QUALIFICAÇÃO DE PESSOAL DE ENSAIOS NÃO DESTRUTIVOS;\r\n*REGISTROS DE QUALIFICAÇÃO DE PROCEDIMENTO DE END.",
    "rowNumber": 212,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "LV - FECHAMENTO DE EQUIPAMENTO",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICOS|LV - FECHAMENTO DE EQUIPAMENTO",
    "notes": "Documentos:\r\n* LISTA DE VERIFICAÇÃO DE FECHAMENTO DE EQUIPAMENTOS.",
    "rowNumber": 214,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PRONTUÁRIOS NR-13_SPIE - EQUIPAMENTOS",
    "databook": "UHDT-D|DATA BOOK C&M|EQP ESTÁTICOS|PRONTUÁRIOS NR-13_SPIE - EQUIPAMENTOS",
    "notes": "Documentos: \r\n* RELATÓRIOS INICIAIS DE INSPEÇÃO INTERNA (RISI.INT.SPIE);\r\n* RELATÓRIOS INICAIS DE INSPEÇÃO EDTERNA + INTERNA (RISI.EDT.INT.SPIE);\r\n* RELATÓRIO DE MEDIÇÃO DE ESPESSURA (US-ME.SPIE);\r\n* CERTIFICADO DE TESTE HIDROSTÁTICO (TH.SPIE);\r\n* PROJETO DE ALTERAÇÃO E REPARO (PAR.SPIE).\nDocumentos:\r\n*MAPA CAMINHO DATA BOOK C&M - ELÉTRICA",
    "rowNumber": 216,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "INSPEÇÃO DE RECEBIMENTO - RIR_ELÉTRICA",
    "databook": "UHDT-D|DATA BOOK C&M|ELÉTRICA|RIR ELÉTRICA",
    "notes": "Documentos: \r\n* LISTA DETALHANDO TODAS AS RIRs CONTIDAS NESTA PASTA POR FAMÍLIA.",
    "rowNumber": 220,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR MOTORES",
    "databook": "UHDT-D|DATA BOOK C&M|ELÉTRICA|RIR ELÉTRICA|MOTORES",
    "notes": "Documentos:\r\n* RIR MOTORES ELÉTRICOS.",
    "rowNumber": 222,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR PAINÉIS_ELÉTRICA",
    "databook": "UHDT-D|DATA BOOK C&M|ELÉTRICA|RIR ELÉTRICA|PAINÉIS",
    "notes": "Documentos:\r\n* RIR PAINÉIS DE ELÉTRICA",
    "rowNumber": 224,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR CABOS_ELÉTRICA",
    "databook": "UHDT-D|DATA BOOK C&M|ELÉTRICA|RIR ELÉTRICA|CABOS",
    "notes": "Documentos:\r\n* RIR CABOS DE ELÉTRICA",
    "rowNumber": 226,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR_TRANSFORMADOR",
    "databook": "UHDT-D|DATA BOOK C&M|ELÉTRICA|RIR ELÉTRICA|TRANSFORMADOR",
    "notes": "Documentos:\r\n* RIR TRANSFORMADORES.",
    "rowNumber": 228,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR_ILUMINAÇÃO",
    "databook": "UHDT-D|DATA BOOK C&M|ELÉTRICA|RIR ELÉTRICA|SISTEMA DE ILUMINAÇÃO",
    "notes": "Documentos:\r\n* RIR LUMINÁRIAS.",
    "rowNumber": 230,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR_INFRAESTRUTURA ELÉTRICA",
    "databook": "UHDT-D|DATA BOOK C&M|ELÉTRICA|RIR ELÉTRICA|INFRAESTRUTURA_ELÉTRICA",
    "notes": "Documentos:\r\n* RIR LEITOS, ELETRODUTOS E ELETROCALHAS.",
    "rowNumber": 232,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR_CAIDA",
    "databook": "UHDT-D|DATA BOOK C&M|ELÉTRICA|RIR ELÉTRICA|CAIDA_ELÉTRICA",
    "notes": "Documentos:\r\n* RIR CAIDAS",
    "rowNumber": 234,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR_TOMADA",
    "databook": "UHDT-D|DATA BOOK C&M|ELÉTRICA|RIR ELÉTRICA|TOMADAS",
    "notes": "Documentos:\r\n* RIR TOMADAS",
    "rowNumber": 236,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PLANOS DE INSPEÇÃO E TESTES - PIT_ELÉTRICA",
    "databook": "UHDT-D|DATA BOOK C&M|ELÉTRICA| PLANO  DE INSPEÇÃO E TESTES - PIT_ELÉTRICA",
    "notes": "Documentos:\r\n* PIT de todos os equipamentos de elétrica e Telecom",
    "rowNumber": 238,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M - MOTOR",
    "databook": "UHDT-D|DATA BOOK C&M|ELÉTRICA| C&M MOTOR_ELÉTRICA",
    "notes": "Documentos:\r\n* RELATÓRIOS DE MONTAGEM DE EQUIPAMENTOS;\r\n* OUTROS, CONFORME NECESSIDADES DO PROJETO - VER RELATÓRIOS DA ET.",
    "rowNumber": 240,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M - PAINÉIS DE ELÉTRICA",
    "databook": "UHDT-D|DATA BOOK C&M|ELÉTRICA| C&M PAINEL_ELÉTRICA",
    "notes": "Documentos:\r\n* RELATÓRIOS DE MONTAGEM DE EQUIPAMENTOS;\r\n* OUTROS, CONFORME NECESSIDADES DO PROJETO - VER RELATÓRIOS DA ET;\r\n* RELATÓRIOS DE MONTAGEM E TESTES DE PAINÉIS ELÉTRICOS.",
    "rowNumber": 242,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M - CABO_ELÉTRICA",
    "databook": "UHDT-D|DATA BOOK C&M|ELÉTRICA| C&M CABO_ELÉTRICA",
    "notes": "Documentos:\r\n* RELATÓRIOS DE LANÇAMENTO / LIGAÇÕES DE CABOS;\r\n* RELATÓRIOS DE TESTES DE CABOS (ISOLAÇÃO/ CONTINUIDADE / CERTIFICAÇÃO DE FASES)\r\n* VER RELATÓRIOS DA ET.;\r\n* RELATÓRIOS DE MONTAGEM DE MCTs (MULTI CABLE TRANSITS).",
    "rowNumber": 244,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M - TRANSFORMADOR",
    "databook": "UHDT-D|DATA BOOK C&M|ELÉTRICA| C&M TRANSFORMADOR",
    "notes": "Documentos:\r\n* RELATÓRIOS DE MONTAGEM DE EQUIPAMENTOS;\r\n* OUTROS, CONFORME NECESSIDADES DO PROJETO - VER RELATÓRIOS DA ET;\r\n* RELATÓRIOS DE MONTAGEM E TESTES DE TRANSFORMADORES",
    "rowNumber": 246,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M - LUMINÁRIAS",
    "databook": "UHDT-D|DATA BOOK C&M|ELÉTRICA| C&M SIST. ILUMINAÇÃO",
    "notes": "Documentos:\r\n* RELATÓRIOS DE MONTAGEM E TESTES DE LUMINÁRIAS;",
    "rowNumber": 248,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M - INFRAESTRUTURA DE ELÉTRICA",
    "databook": "UHDT-D|DATA BOOK C&M|ELÉTRICA| C&M INFRAESTRUTURA_ELÉTRICA",
    "notes": "Documentos:\r\n* RELATÓRIO DE MONTAGEM DE LEITOS, ELETRODUTOS E ELETROCALHAS;\r\n* RELATÓRIOS DE MONTAGEM DE BANDEJAS / ELETRODUTOS / ELETROCALHAS;\r\n* RELATÓRIOS DE MONTAGEM DE SUPORTES.",
    "rowNumber": 250,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M - CAIDAS",
    "databook": "UHDT-D|DATA BOOK C&M|ELÉTRICA| C&M CAIDA_ELÉTRICA",
    "notes": "Documentos:\r\n* RELATÓRIOS DE MONTAGEM DE CAIDAS DE JUNÇÃO (JBs)",
    "rowNumber": 252,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M - TOMADAS",
    "databook": "UHDT-D|DATA BOOK C&M|ELÉTRICA| C&M TOMADA",
    "notes": "Documentos:\r\n* RELATÓRIOS DE MONTAGEM DE TOMADAS;\r\n* RELATÓRIOS DE MONTAGEM E TESTES CIRCUITOS DE ILUMINAÇÃO.",
    "rowNumber": 254,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "QUALIFICAÇÃO EQUIPE_ELÉTRICA",
    "databook": "UHDT-D|DATA BOOK C&M|ELÉTRICA|QUALIFICAÇÃO DA EQUIPE_ELÉTRICA",
    "notes": "Documentos:\r\n* MAPA DE DOCUMENTAÇÃO\r\n* REGISTROS DE QUALIFICAÇÃO DA EQUIPE",
    "rowNumber": 256,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PRONTUÁRIOS NR-10",
    "databook": "UHDT-D|DATA BOOK C&M|ELÉTRICA| PRONTUÁRIO NR-10",
    "notes": "Documentos: \r\n* PRONTUÁRIO UNIDADES (U-39s, SE-3200, U-32 e CANTEIRO)\r\n* TERMO DE CONFORMIDADE DE EQUIPAMENTOS E INSTALAÇÕES \"ED\"\r\n* QUALIFICAÇÃO DA EQUIPE NR-10.\nDocumentos:\r\n*MAPA CAMINHO DATA BOOK C&M - TELECOM",
    "rowNumber": 258,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "INSPEÇÃO DE RECEBIMENTO - RIR_TELECOM",
    "databook": "UHDT-D|DATA BOOK C&M|TELECOM|RIR_TELECOM",
    "notes": "Documentos: \r\n* LISTA DETALHANDO TODAS AS RIRs CONTIDAS NESTA PASTA POR FAMÍLIA.",
    "rowNumber": 262,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR SUÍTE",
    "databook": "UHDT-D|DATA BOOK C&M|TELECOM| RIR SUÍTE_TELECOM",
    "notes": "Documentos:\r\n* RIR MOTORES ELÉTRICOS.",
    "rowNumber": 264,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR PAINEL_TELECOM",
    "databook": "UHDT-D|DATA BOOK C&M|TELECOM| RIR PAINEL_TELECOM",
    "notes": "Documentos:\r\n* RIR PAINÉIS.",
    "rowNumber": 266,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR CABO_TELECOM",
    "databook": "UHDT-D|DATA BOOK C&M|TELECOM| RIR CABO_TELECOM",
    "notes": "Documentos:\r\n* RIR CABOS.",
    "rowNumber": 268,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR DIO_TELECOM",
    "databook": "UHDT-D|DATA BOOK C&M|TELECOM| RIR DIO",
    "notes": "Documentos:\r\n* RIR TRANSFORMADORES.",
    "rowNumber": 270,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR CÂMERA DE VÍDEO",
    "databook": "UHDT-D|DATA BOOK C&M|TELECOM| RIR CÂMERA DE VÍDEO",
    "notes": "Documentos:\r\n* RIR CÂMERAS",
    "rowNumber": 272,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR INFRAESTRUTURA_TELECOM",
    "databook": "UHDT-D|DATA BOOK C&M|TELECOM|RIR INFRAESTRUTURA_TELECOM",
    "notes": "Documentos:\r\n* RIR LEITOS, ELETRODUTOS E ELETROCALHAS.",
    "rowNumber": 274,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR_CAIDA",
    "databook": "UHDT-D|DATA BOOK C&M|TELECOM|RIR CAIDA_TELECOM",
    "notes": "Documentos:\r\n* RIR CAIDAS",
    "rowNumber": 276,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PLANOS DE INSPEÇÃO E TESTES - PIT_TELECOM",
    "databook": "UHDT-D|DATA BOOK C&M|TELECOM|PLANO  DE INSPEÇÃO E TESTES - PIT_TELECOM",
    "notes": "Documentos:\r\n* PLANOS DE INSPEÇÃO E TESTES - PIT_EQUIPAMENTOS TELECOM",
    "rowNumber": 278,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M DIO",
    "databook": "UHDT-D|DATA BOOK C&M|TELECOM|C&M DIO",
    "notes": "Documentos:\r\n* RELATÓRIOS DE MONTAGEM DE EQUIPAMENTOS;\r\n* RELATÓRIOS DE ANÁLISE DE TENSÕES;\r\n* OUTROS, CONFORME NECESSIDADES DO PROJETO - VER RELATÓRIOS DA ET.",
    "rowNumber": 280,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M PAINÉIS DE TELECOM",
    "databook": "UHDT-D|DATA BOOK C&M|TELECOM|C&M PAINEL_TELECOM",
    "notes": "Documentos:\r\n* RELATÓRIOS DE MONTAGEM DE EQUIPAMENTOS;\r\n* RELATÓRIOS DE ANÁLISE DE TENSÕES;\r\n* OUTROS, CONFORME NECESSIDADES DO PROJETO - VER RELATÓRIOS DA ET;\r\n* RELATÓRIOS DE MONTAGEM E TESTES DE PAINÉIS ELÉTRICOS.",
    "rowNumber": 282,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M DE CABO",
    "databook": "UHDT-D|DATA BOOK C&M|TELECOM|C&M CABO_TELECOM",
    "notes": "Documentos:\r\n*RELATÓRIOS DE LANÇAMENTO / LIGAÇÕES DE CABOS E FIBRAS ÓPTICAS;\r\n* RELATÓRIOS DE TESTES DE CABOS (ISOLAÇÃO/ CONTINUIDADE / CERTIFICAÇÃO DE FASES)\r\n* VER RELATÓRIOS DA ET.;\r\n* RELATÓRIOS DE MONTAGEM DE MCTs (MULTI CABLE TRANSITS).",
    "rowNumber": 284,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M DE CÂMERA DE VÍDEO",
    "databook": "UHDT-D|DATA BOOK C&M|TELECOM|C&M CÂMERA DE VÍDEO",
    "notes": "Documentos:\r\n* RELATÓRIOS DE MONTAGEM DE EQUIPAMENTOS;\r\n* RELATÓRIOS DE ANÁLISE DE TENSÕES;\r\n* OUTROS, CONFORME NECESSIDADES DO PROJETO - VER RELATÓRIOS DA ET;\r\n* RELATÓRIOS DE MONTAGEM E TESTES DE TRANSFORMADORES",
    "rowNumber": 286,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M SUÍTE",
    "databook": "UHDT-D|DATA BOOK C&M|TELECOM|C&M SUÍTE_TELECOM",
    "notes": "Documentos:\r\n* RELATÓRIOS DE MONTAGEM E TESTES DE EQUIPAMENTOS;\r\n* RELATÓRIOS DE TESTES DE COMUNICAÇÃO;\r\n* RELATÓRIOS DE ANÁLISE DE TENSÕES",
    "rowNumber": 288,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M INFRAESTRUTURA DE TELECOM",
    "databook": "UHDT-D|DATA BOOK C&M|TELECOM|C&M INFRAESTRUTURA_TELECOM",
    "notes": "Documentos:\r\n* RELATÓRIO DE MONTAGEM DE LEITOS, ELETRODUTOS E ELETROCALHAS;\r\n* RELATÓRIOS DE MONTAGEM DE BANDEJAS / ELETRODUTOS / ELETROCALHAS;\r\n* RELATÓRIOS DE MONTAGEM DE SUPORTES.",
    "rowNumber": 290,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M CAIDAS",
    "databook": "UHDT-D|DATA BOOK C&M|TELECOM|C&M CAIDA_TELECOM",
    "notes": "Documentos:\r\n* RELATÓRIOS DE MONTAGEM DE CAIDAS DE JUNÇÃO (JBs)\nDocumentos:\r\n*MAPA CAMINHO DATA BOOK C&M - INSTRUMENTAÇÃO",
    "rowNumber": 292,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "INSPEÇÃO DE RECEBIMENTO - RIR_INSTRUMENTAÇÃO",
    "databook": "UHDT-D|DATA BOOK C&M|INSTRUMENTAÇÃO|RIR_INSTRUMENTAÇÃO",
    "notes": "Documentos: \r\n* LISTA DETALHANDO TODAS AS RIRs POR FAMÍLIA.",
    "rowNumber": 296,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR INTRUMENTOS",
    "databook": "UHDT-D|DATA BOOK C&M|INSTRUMENTAÇÃO|RIR INSTRUMENTOS",
    "notes": "",
    "rowNumber": 298,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR PAINEL_INSTRUMENTAÇÃO",
    "databook": "UHDT-D|DATA BOOK C&M|INSTRUMENTAÇÃO|RIR PAINÉIS_INSTRUMENTAÇÃO",
    "notes": "",
    "rowNumber": 300,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR CABOS_INSTRUMENTAÇÃO",
    "databook": "UHDT-D|DATA BOOK C&M|INSTRUMENTAÇÃO|RIR CABOS_INSTRUMENTAÇÃO",
    "notes": "",
    "rowNumber": 302,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RIR INFRAESTRUTURA_INSTRUMENTAÇÃO",
    "databook": "UHDT-D|DATA BOOK C&M|INSTRUMENTAÇÃO|RIR INFRAESTRUTURA_INSTRUMENTAÇÃO",
    "notes": "",
    "rowNumber": 304,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PLANOS DE INSPEÇÃO E TESTES - PIT DE INSTRUMENTAÇÃO",
    "databook": "UHDT-D|DATA BOOK C&M|INSTRUMENTAÇÃO|PLANO  DE INSPEÇÃO E TESTES - PIT_INSTRUMENTAÇÃO",
    "notes": "",
    "rowNumber": 306,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M DE INSTRUMENTOS",
    "databook": "UHDT-D|DATA BOOK C&M|INSTRUMENTAÇÃO|C&M DE INSTRUMENTOS",
    "notes": "Documentos: \r\n* RELATÓRIOS DE MONTAGEM DE INSTRUMENTOS.",
    "rowNumber": 308,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M INFRAESTRUTURA DE INSTRUMENTAÇÃO",
    "databook": "UHDT-D|DATA BOOK C&M|INSTRUMENTAÇÃO|C&M DE INFRAESTRUTURA_INSTRUMENTAÇÃO",
    "notes": "Documentos:\r\n*RELATÓRIOS DE MONTAGEM DE BANDEJAS / ELETRODUTOS / ELETROCALHAS\r\n* RELATÓRIOS DE MONTAGEM DE SUPORTES;\r\n* RELATÓRIOS DE MONTAGEM DE TUBINGS",
    "rowNumber": 310,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M DE CAIDAS DE INSTRUMENTAÇÃO",
    "databook": "UHDT-D|DATA BOOK C&M|INSTRUMENTAÇÃO|C&M CAIDA_INSTRUMENTAÇÃO",
    "notes": "Documentos:\r\n*RELATÓRIOS DE MONTAGEM DE CAIDAS DE JUNÇÃO (JBs)",
    "rowNumber": 312,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M DE CABOS DE INSTRUMENTAÇÃO",
    "databook": "UHDT-D|DATA BOOK C&M|INSTRUMENTAÇÃO|C&M CABO_INSTRUMENTAÇÃO",
    "notes": "Documentos:\r\n*RELATÓRIOS DE LANÇAMENTO / LIGAÇÕES DE CABOS;\r\n* RELATÓRIOS DE MONTAGEM DE MCTs (MULTI CABLE TRANSITS);",
    "rowNumber": 314,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M PAINÉIS DE INSTRUMENTAÇÃO",
    "databook": "UHDT-D|DATA BOOK C&M|INSTRUMENTAÇÃO|C&M PAINEL_INSTRUMENTAÇÃO",
    "notes": "Documentos:\r\n*RELATÓRIO DE MONTAGEM E TESTES DE PAINÉIS, REMOTAS, ETC.",
    "rowNumber": 316,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "CERTIFICADOS CALIBRAÇÃO E TESTES DE INSTRUMENTOS",
    "databook": "UHDT-D|DATA BOOK C&M|INSTRUMENTAÇÃO|CERTIFICADO DE CALIBRAÇÃO E TESTE DE INSTRUMENTOS",
    "notes": "Documentos:\r\n*CERTIFICADOS DE CALIBRAÇÃO DE INSTRUMENTOS, VÁLVULAS DE SEGURANÇA_ALÍVIO E DISCOS DE RUPTURA\nDocumentos:\r\n*MAPA CAMINHO DATA BOOK C&M - HVAC",
    "rowNumber": 318,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "RELATÓRIOS DE INSPEÇÃO DE RECEBIMENTO - RIR HVAC",
    "databook": "UHDT-D|DATA BOOK C&M|HVAC|CERTIFICADO DE CALIBRAÇÃO E TESTE DE INSTRUMENTOS",
    "notes": "Documentos:\r\n* RIR SISTEMA DE HVAC",
    "rowNumber": 322,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "PLANOS DE INSPEÇÃO E TESTES - PIT",
    "databook": "UHDT-D|DATA BOOK C&M|HVAC|PLANO  DE INSPEÇÃO E TESTES - PIT_HVAC",
    "notes": "Documentos:\r\n* PLANOS DE INSPEÇÃO E TESTES - PIT DO SISTEMA HVAC",
    "rowNumber": 324,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "C&M",
    "databook": "UHDT-D|DATA BOOK C&M|HVAC|C&M DE HVAC",
    "notes": "Documentos:\r\n* RELATÓRIOS DE CONSTRUÇÃO / INSPEÇÃO DAS BASES;\r\n* RELATÓRIOS DE MONTAGEM (ALINHAMENTO / NIVELAMENTO);\r\n* RELATÓRIOS DE TUBULAÇÕES (PARALELISMO / ALINHAMENTO / CONCENTRICIDADE E AFASTAMENTO ENTRE FLANGES);\r\n* RELATÓRIOS DE TORQUEAMENTO;\r\n* RELATÓRIOS DE INSTALAÇÃO DE ISOLAMENTOS TÉRMICOS\r\n* DEMAIS RELATÓRIOS DE MONTAGEM, VERIFICAR ITENS DESCRITOS NA ET.",
    "rowNumber": 326,
    "sourceSheet": "CAMINHO DB_SIGEM"
  },
  {
    "description": "ENSAIOS E TESTES FUNCIONAIS",
    "databook": "UHDT-D|DATA BOOK C&M|HVAC|ENSAIOS E TESTES DE HVAC",
    "notes": "Documentos:\r\n* CERTIFICADO DE CONDICIONAMENTO DOS DUTOS DE VENTILAÇÃO ASSOCIADAS (LIMPEZA, ETC.);\r\n* RELATÓRIOS DE TESTES FUNCIONAIS (REGISTROS DE NÍVEL DE RUÍDO, VIBRAÇÃO, ETC.).",
    "rowNumber": 328,
    "sourceSheet": "CAMINHO DB_SIGEM"
  }
]; })(typeof globalThis !== "undefined" ? globalThis : this);

