const assert=require('node:assert/strict');
const M=require('./discipline_document_matrix.js');
const catalog=M.catalog;
const input={app:'RECON',discipline:'tubulacao',phase:'executivo',sources:[]};
const rule=catalog.rules.find(r=>r.norm==='N-1692' && r.section==='10');
assert.equal(M.audit(input).summary.blocks,0);
assert.equal(M.audit({...input,phase:'basico'}).rules.some(r=>r.section==='10'),false);
assert.equal(M.audit({...input,phase:'basico'}).rules.find(r=>r.section==='7').normativeKind,'recommended');
assert.throws(()=>M.audit({...input,discipline:'940'}));
assert.throws(()=>M.audit({...input,phase:''}));
const source={kind:'LD',name:'LD.xlsx',records:[{document:'DE-5290.00-22313-940-CHZ-001',title:'DESENHO ISOMETRICO',discipline:'TUBULAÇÃO',EAP:'1.1'}]};
const saved=JSON.stringify(source);
const report=M.audit({...input,sources:[source]});
assert.equal(JSON.stringify(source),saved,'Não altera a LD');
assert.equal(report.rules.find(r=>r.ruleId===rule.id).status,'identified');
assert.equal(report.rules.find(r=>r.ruleId===rule.id).outcome,'INFORMAÇÃO');
assert.equal(report.rules.find(r=>r.ruleId===rule.id).evidence[0].inPlannedDocuments,null);
const result=(s,extra={})=>M.audit({...input,...extra,sources:[s]}).rules.find(r=>r.ruleId===rule.id);
assert.equal(result({...source,kind:'SCON'}).status,'candidate');
assert.equal(result({...source,records:[{...source.records[0],discipline:'ELÉTRICA'}]}).status,'not-identified');
assert.equal(result({...source,records:[{...source.records[0],discipline:'',serviceClass:'940'}]}).status,'candidate','Classe não comprova disciplina');
assert.equal(result(source,{scope:'1.2'}).status,'not-identified');
assert.equal(result(source,{scope:'1.1'}).status,'identified');
assert.equal(result({...source,records:[{document:'DE-001',discipline:'TUBULACAO'}]}).status,'not-identified','Só código não comprova família');
const planned={kind:'Documentos Previstos',snapshotId:'P1',records:[{document:source.records[0].document}]};
assert.equal(M.audit({...input,sources:[source,planned]}).rules.find(r=>r.ruleId===rule.id).evidence[0].inPlannedDocuments,true);
assert.equal(M.audit({...input,sources:[planned]}).summary.identified,0);
assert.equal(M.audit({...input,phase:'feed'}).summary.total,0,'Ausência de cobertura não é conformidade');
assert.equal(M.audit({...input,discipline:'civil'}).rules.every(r=>r.condition.includes('concreto')),true);
const historical=JSON.stringify(report); source.records.push({...source.records[0],document:'DE-002'});
assert.equal(JSON.parse(historical).rules.find(r=>r.ruleId===rule.id).evidenceCount,1,'Snapshot histórico independente');
assert.deepEqual(M.readSnapshot(JSON.parse(historical)).summary,report.summary);
assert.throws(()=>M.readSnapshot({...report,catalogVersion:'invalid'}));
assert.throws(()=>M.readSnapshot({...report,context:{discipline:'SMS',phase:'executivo'}}));
const bad=JSON.parse(historical);bad.normativeSources['N-1692'].sha256='outro';assert.throws(()=>M.readSnapshot(bad));
const tampered=JSON.parse(historical);tampered.summary.alerts=0;tampered.rules[0].outcome='BLOQUEIO';assert.equal(M.readSnapshot(tampered).rules[0].outcome,'ALERTA');
assert.match(M.csv(report),/NORMA/);
const formula=JSON.parse(historical);formula.rules[0].label='=SUM(A1)';assert.match(M.csv(formula),/"'=SUM\(A1\)"/);
assert.equal(new Set(catalog.rules.map(r=>r.id)).size,catalog.rules.length);
assert.equal(catalog.rules.filter(r=>r.norm==='N-1883').length,65);
assert.ok(catalog.rules.every(r=>catalog.sources[r.norm]?.sha256.length===64));
// Volume realista: cada evidência exportada é limitada, a contagem total permanece.
const records=Array.from({length:10000},(_,i)=>({document:'DE-'+i,title:'DESENHO ISOMETRICO',discipline:'TUBULACAO'}));
const volume=result({kind:'LD',records});assert.equal(volume.evidence.length,20);assert.equal(volume.evidenceCount,10000);
console.log('discipline_document_matrix: ok — fases, disciplina, fontes, caráter consultivo, rastreio, snapshots e volume');
