(function (root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  root.RECONDocumentCodingCVProfile = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

  const SOURCE = Object.freeze({
    id: "ET-5290.00-22000-910-1LV-002",
    revision: "0",
    date: "2024-10-18",
    title: "ANEXO X – DIRETRIZ DE QUALIDADE – APÊNDICE C – CONDIÇÕES ESPECÍFICAS DE QUALIFICAÇÃO DA EQUIPE CONTRATADA",
    scope: "RNEST / TREM 2",
    note: "Perfil contratual específico. Não deve ser tratado como regra universal para contratos externos ao RNEST/T2.",
  });

  const SUPPLEMENTAL_SOURCES = Object.freeze([
    Object.freeze({ id: "ET-5290.00-22000-910-1LV-004", revision: "0", title: "ANEXO X – DIRETRIZ PARA GESTÃO DA QUALIDADE", scope: "qualidade e PIT" }),
    Object.freeze({ id: "ET-0000.00-0000-972-PEI-003", revision: "E", title: "REQUISITO GERAL DE INSPEÇÃO DE FABRICAÇÃO", scope: "qualificação/certificação de inspeção de fabricação" }),
    Object.freeze({ id: "ET-5290.00-2000-971-PEI-005", revision: "C", title: "EXECUÇÃO DE INSPEÇÃO EM VÁLVULAS INDUSTRIAIS", scope: "inspeção de válvulas" }),
    Object.freeze({ id: "MD-5290.00-22313-950-1LV-007", revision: "0", title: "ANEXO I-D – MEMORIAL DESCRITIVO DE INSPEÇÃO", scope: "inspeção de recebimento/RIR" }),
    Object.freeze({ id: "MD-5290.00-22313-950-1LV-006", revision: "0", title: "ANEXO I-B – MEMORIAL DESCRITIVO DE AJUSTES E REPAROS", scope: "inspeção, reparos e ajustes" }),
  ]);

  const GENERAL = Object.freeze([
    Object.freeze({ id: "proof-cv", item: "2.2.1", label: "Curriculum vitae", detail: "A experiência profissional deve ser apresentada no curriculum vitae." }),
    Object.freeze({ id: "proof-ctps", item: "2.2.1", label: "Carteira de trabalho", detail: "A experiência deve também ser comprovada pela carteira de trabalho." }),
    Object.freeze({ id: "proof-council", item: "2.2.1", label: "Registro no conselho de classe", detail: "Quando aplicável à função, o respectivo registro profissional deve integrar a comprovação." }),
    Object.freeze({ id: "petrobras-approval", item: "2.2.2", label: "Aprovação da Fiscalização PETROBRAS", detail: "Qualificação/experiência somente pode ser flexibilizada mediante solicitação prévia e aprovação exclusiva da Fiscalização PETROBRAS." }),
    Object.freeze({ id: "exclusive", item: "2.2.3", label: "Mobilização exclusiva", detail: "O profissional deve ser mobilizado exclusivamente para o Contrato e não acumular funções, salvo autorização expressa da Fiscalização PETROBRAS." }),
    Object.freeze({ id: "contract-docs", item: "2.2.4", label: "Conjunto contratual", detail: "A sistemática de aprovação e equipe mínima deve observar todos os documentos contratuais, não apenas o Apêndice C." }),
    Object.freeze({ id: "advance-30", item: "2.2.5", label: "Antecedência de 30 dias", detail: "A documentação comprobatória deve ser apresentada 30 dias corridos antes da mobilização." }),
  ]);

  function role(id, item, title, aliases, options) {
    return Object.freeze(Object.assign({
      id, item, title, aliases: aliases || [], group: "", degreeAny: [], degreeRequired: false,
      council: false, minYears: null, specificExperience: [], credentials: [], courses: [], projectEvidence: [], notes: [],
    }, options || {}));
  }

  const ROLES = Object.freeze([
    role("contract-manager", "3.1.1.1", "Gerente do Contrato", ["gerente do contrato", "gerente de contrato"], { group: "Gerenciamento", degreeAny: ["engenharia"], degreeRequired: true, council: true, minYears: 8, specificExperience: [{ years: 5, context: "gerenciamento de obras de grande porte" }], projectEvidence: ["projetos, construção e montagem de unidades industriais de petróleo e/ou petroquímica"] }),
    role("engineering-project-manager", "3.1.2.1", "Gerente do Projeto de Engenharia", ["gerente do projeto de engenharia", "gerente de engenharia"], { group: "Gerenciamento", degreeAny: ["engenharia"], degreeRequired: true, council: true, minYears: 8, specificExperience: [{ years: 3, context: "gerenciamento de projetos executivos de grande porte em petróleo e/ou petroquímica" }], courses: ["ISO 9001", "ISO 14001", "ISO 45001"], notes: ["Deve demonstrar domínio das ferramentas de gerenciamento de projetos e softwares utilizados."] }),
    role("construction-manager", "3.1.3.1", "Gerente de Construção e Montagem", ["gerente de construção e montagem", "gerente de construcao e montagem"], { group: "Gerenciamento", degreeAny: ["engenharia"], degreeRequired: true, council: true, minYears: 8, specificExperience: [{ years: 3, context: "coordenação de equipes de obras industriais de petróleo e/ou petroquímica" }] }),
    role("administrative-manager", "3.1.4.1", "Gerente Administrativo", ["gerente administrativo"], { group: "Gerenciamento", degreeAny: ["administração de empresas", "administracao de empresas"], degreeRequired: true, council: true, minYears: 3, specificExperience: [{ years: 3, context: "gerenciamento ou coordenação administrativa" }] }),
    role("supply-manager", "3.1.5.1", "Gerente de Suprimento", ["gerente de suprimento", "gerente de suprimentos"], { group: "Gerenciamento", degreeAny: ["engenharia", "economia", "administração", "administracao"], degreeRequired: true, council: true, minYears: 8, projectEvidence: ["suprimentos e logística de obras industriais de petróleo e/ou petroquímica"] }),
    role("planning-manager", "3.1.6.1", "Gerente de Planejamento e Controle", ["gerente de planejamento e controle", "gerente de planejamento"], { group: "Gerenciamento", degreeAny: ["engenharia"], degreeRequired: true, council: true, minYears: 8, specificExperience: [{ years: 3, context: "supervisão de equipe de planejamento de obras industriais" }], credentials: ["PMP ou MBA em Gestão de Projetos (condicionado à aprovação da PETROBRAS)"], notes: ["Sólidos conhecimentos de metodologias e ferramentas de planejamento, controle e gestão do tempo."] }),
    role("quality-manager", "3.1.7.1", "Gerente da Qualidade", ["gerente da qualidade", "gerente de qualidade"], { group: "Gerenciamento", degreeAny: ["engenharia"], degreeRequired: true, council: true, minYears: 5, projectEvidence: ["implantação, desenvolvimento e manutenção de Sistemas de Gestão da Qualidade em obras de grande porte"], courses: ["NBR ISO 9001"] }),
    role("sms-manager", "3.1.8.1", "Gerente de Segurança, Meio Ambiente, Saúde e Comunicação/Responsabilidade Social", ["gerente de segurança", "gerente de sms", "gerente de segurança meio ambiente saúde"], { group: "Gerenciamento", degreeAny: ["engenharia"], degreeRequired: true, council: true, minYears: 8, projectEvidence: ["implantação, desenvolvimento e manutenção de sistemas de gestão em obras de grande porte"], courses: ["ISO 45001", "NBR ISO 14001"] }),
    role("commissioning-manager", "3.1.9.1", "Gerente de Comissionamento", ["gerente de comissionamento"], { group: "Gerenciamento", degreeAny: ["engenharia"], degreeRequired: true, council: true, minYears: 8, projectEvidence: ["comissionamento de unidades industriais de petróleo e/ou petroquímica"] }),

    role("civil-responsible", "3.2.1.1", "Responsável pelos Serviços de Construção Civil", ["responsável construção civil", "responsavel construcao civil", "engenheiro civil responsável"], { group: "Execução – Civil", degreeAny: ["engenharia civil"], degreeRequired: true, council: true, minYears: 5, projectEvidence: ["condução de serviços de construção civil em obras de grande porte"] }),
    role("civil-supervisor", "3.2.1.2", "Supervisor de Construção Civil (Mestre de Obras)", ["supervisor de construção civil", "mestre de obras"], { group: "Execução – Civil", minYears: 3, projectEvidence: ["execução de serviços em construção civil e experiência em obras de grande porte"] }),
    role("lifting-responsible", "3.2.2.1", "Responsável pelos Serviços de Movimentação de Cargas", ["responsável movimentação de cargas", "engenheiro movimentação de cargas"], { group: "Execução – Movimentação de Cargas", degreeAny: ["engenharia mecânica", "engenharia mecanica"], degreeRequired: true, council: true, minYears: 5, projectEvidence: ["planejamento, projeto e coordenação de operações de movimentação de diversos tipos e portes de cargas"] }),
    role("rigger-supervisor", "3.2.2.2", "Supervisor de Movimentação de Cargas – Rigger", ["rigger", "supervisor de movimentação de cargas"], { group: "Execução – Movimentação de Cargas", council: true, minYears: 6, projectEvidence: ["supervisão de levantamentos de cargas em obras de construção de unidades de processo"] }),
    role("nr13-ph", "3.2.3.1.a", "Profissional Habilitado (PH) – NR-13", ["profissional habilitado nr-13", "ph nr-13", "nr13"], { group: "Qualidade – Mecânica/Tubulação/Estáticos", degreeAny: ["engenharia mecânica", "engenharia mecanica", "engenharia metalúrgica", "engenharia metalurgica", "metalurgia"], degreeRequired: true, council: true, credentials: ["qualificação em entidade reconhecida"], specificExperience: [{ years: 0.5, context: "paradas de manutenção em refinaria, química ou petroquímica na atividade de inspeção de equipamentos e instalações" }], projectEvidence: ["experiência como PH em construção de unidades de processo de óleo e gás"] }),
    role("equipment-inspector-static", "3.2.3.1.b", "Inspetor de Equipamentos – Estáticos/Tubulação", ["inspetor de equipamentos", "inspetor de equipamento"], { group: "Qualidade – Mecânica/Tubulação/Estáticos", minYears: 5, credentials: ["Portaria INMETRO nº 537/2015"], projectEvidence: ["inspeção de equipamentos de unidades de processo de óleo e gás"] }),
    role("industrial-montage-responsible", "3.2.3.2.a", "Responsável pelos Serviços de Montagem Industrial", ["responsável montagem industrial", "responsavel montagem industrial"], { group: "Execução – Montagem Industrial", degreeAny: ["engenharia"], degreeRequired: true, council: true, minYears: 5, projectEvidence: ["condução de serviços de construção e montagem em obras de grande porte"] }),
    role("industrial-montage-supervisor", "3.2.3.2.b", "Supervisor de Montagem Industrial", ["supervisor de montagem industrial", "supervisor de montagem"], { group: "Execução – Montagem Industrial", minYears: 5, projectEvidence: ["fabricação e montagem de estruturas metálicas, tubulação industrial e equipamentos estáticos em obras de grande porte"] }),
    role("static-commissioning-supervisor", "3.2.3.2.c", "Supervisor de Comissionamento – Tubulação/Equipamentos Estáticos", ["supervisor de comissionamento tubulação", "supervisor de comissionamento equipamentos estáticos"], { group: "Execução – Montagem Industrial", minYears: 6, projectEvidence: ["comissionamento de tubulação industrial e equipamentos estáticos em obras de grande porte"] }),
    role("welding-responsible", "3.2.3.2.d", "Responsável pelos Serviços de Soldagem", ["responsável soldagem", "responsavel soldagem", "supervisor de soldagem"], { group: "Execução – Soldagem", minYears: 3, projectEvidence: ["supervisão de serviços de solda em obras de grande porte"] }),
    role("welder-operator", "3.2.3.2.e / 3.4", "Soldador / Operador de Soldagem", ["soldador", "operador de soldagem"], { group: "Execução – Soldagem", credentials: ["ASME Section IX ou norma aplicável", "qualificação pela CONTRATADA ou entidade reconhecida"], notes: ["Regras de permanência/requalificação dos itens 3.4.1 a 3.4.3 devem ser verificadas."] }),
    role("scaffolding-responsible", "3.2.3.2.f", "Responsável por Montagem de Andaimes", ["responsável andaime", "responsavel andaime", "montagem de andaimes"], { group: "Execução – Andaimes", minYears: 5, projectEvidence: ["projeto ou montagem de estruturas de andaimes"] }),
    role("equipment-inspector-dynamic", "3.2.4.1.a", "Inspetor de Equipamentos – Dinâmicos", ["inspetor de equipamentos dinâmicos", "inspetor equipamentos dinamicos"], { group: "Qualidade – Dinâmicos", minYears: 5, credentials: ["Portaria INMETRO nº 537/2015", "ABRAMAN PNQC-NR-P4.10-12"], projectEvidence: ["inspeção de equipamentos de unidades de processo"] }),
    role("dynamic-montage-responsible", "3.2.4.2.a", "Responsável por Montagem de Equipamentos Dinâmicos", ["responsável equipamentos dinâmicos", "responsavel equipamentos dinamicos"], { group: "Execução – Dinâmicos", degreeAny: ["engenharia", "formação técnica", "formacao tecnica"], degreeRequired: true, council: true, minYears: 5, projectEvidence: ["condução de serviços de construção e montagem em obras de grande porte"] }),
    role("conditioning-supervisor", "3.2.4.2.b", "Supervisor de Condicionamento – Equipamentos Dinâmicos", ["supervisor de condicionamento"], { group: "Execução – Dinâmicos", minYears: 3, projectEvidence: ["condicionamento de equipamentos dinâmicos em obras de unidades de processo"] }),
    role("refractory-insulation-inspector", "3.2.5.1", "Inspetor de Refratários e Isolamento Térmico Industrial", ["inspetor de refratários", "inspetor de refratarios", "inspetor de isolamento térmico", "inspetor de isolamento termico"], { group: "Qualidade – Refratários/Isolamento", minYears: 5, specificExperience: [{ years: 0.5, context: "serviços de isolamento térmico, inclusive com uso de acesso por cordas" }], projectEvidence: ["inspeção ou supervisão de aplicação de revestimento refratário no setor industrial"], notes: ["Deve estar capacitado para preparação de superfície e mapeamento das janelas de inspeção."] }),
    role("electrical-responsible", "3.2.6.1", "Responsável pelos Serviços de Eletricidade", ["responsável eletricidade", "responsavel eletricidade", "responsável elétrico"], { group: "Execução – Elétrica", degreeAny: ["engenharia elétrica", "engenharia eletrica"], degreeRequired: true, council: true, minYears: 5, credentials: ["Profissional Qualificado e Habilitado em NR-10"], courses: ["NR-10"], projectEvidence: ["montagem e testes de sistemas elétricos em obras de grande porte"] }),
    role("electrical-montage-supervisor", "3.2.6.2", "Supervisor de Montagem de Sistemas Elétricos", ["supervisor montagem elétrica", "supervisor montagem eletrica"], { group: "Execução – Elétrica", council: true, minYears: 5, courses: ["NR-10"], projectEvidence: ["supervisão de montagem elétrica industrial em obras de construção de grande porte"] }),
    role("instrumentation-responsible", "3.2.7.1", "Responsável pelos Serviços de Instrumentação", ["responsável instrumentação", "responsavel instrumentacao"], { group: "Execução – Instrumentação", degreeAny: ["engenharia elétrica", "engenharia eletrica", "engenharia eletrônica", "engenharia eletronica", "automação", "automacao"], degreeRequired: true, council: true, minYears: 5, courses: ["NR-10"], projectEvidence: ["montagem e testes de sistemas de instrumentação em obras de grande porte"] }),
    role("instrumentation-montage-supervisor", "3.2.7.2", "Supervisor de Montagem de Sistemas de Instrumentação", ["supervisor de instrumentação", "supervisor montagem instrumentação"], { group: "Execução – Instrumentação", council: true, minYears: 5, specificExperience: [{ years: 3, context: "cargo de Supervisor em Montagem de Sistemas de Instrumentação Industrial" }], courses: ["NR-10"] }),
    role("calibration-test-supervisor", "3.2.7.3", "Supervisor de Calibração e Testes", ["supervisor de calibração", "supervisor de calibracao", "supervisor de testes"], { group: "Execução – Instrumentação", degreeAny: ["técnico em eletrotécnica", "tecnico em eletrotecnica", "técnico em instrumentação", "tecnico em instrumentacao", "eletrônica industrial", "eletronica industrial"], degreeRequired: true, minYears: 5, specificExperience: [{ years: 3, context: "cargo de Supervisor em calibração de instrumentos e testes de malhas" }], courses: ["NR-10"] }),
    role("sdcd-clp-specialist", "3.2.7.4", "Especialista em Sistemas de Supervisão e Controle (SDCD/CLP)", ["especialista sdcd", "especialista clp", "sistemas de supervisão e controle"], { group: "Execução – Automação", minYears: 5, projectEvidence: ["desenvolvimento de lógica e telas de supervisório"], credentials: ["vínculo com fabricante dos sistemas ou empresa certificada pelo fabricante"] }),
    role("industrial-networks-specialist", "3.2.7.5", "Especialista em Redes Industriais", ["especialista em redes industriais", "profibus", "foundation fieldbus"], { group: "Execução – Automação", courses: ["ETHERNET – 24 h-aula", "RS-485 – 24 h-aula", "Profibus-DP – 24 h-aula", "FOUNDATION Fieldbus – 24 h-aula", "NR-10"], credentials: ["certificações previstas no Anexo I – Apêndice 12 – Automação e Redes Industriais"] }),
    role("commissioning-engineer", "3.2.8.1", "Engenheiro de Comissionamento", ["engenheiro de comissionamento"], { group: "Comissionamento", degreeAny: ["engenharia"], degreeRequired: true, council: true, minYears: 5, specificExperience: [{ years: 3, context: "coordenação de trabalhos de comissionamento" }], projectEvidence: ["comissionamento de unidades de petróleo e/ou petroquímica"] }),
    role("commissioning-supervisor", "3.2.8.2", "Supervisor de Comissionamento", ["supervisor de comissionamento"], { group: "Comissionamento", minYears: 5, projectEvidence: ["comissionamento de processos industriais, tubulação, equipamentos estáticos/dinâmicos, elétrica ou instrumentação em unidades de processo"] }),
    role("interfaces-engineer", "3.2.9.1", "Engenheiro de Interfaces", ["engenheiro de interfaces", "engenheiro interface"], { group: "Interfaces", degreeAny: ["engenharia"], degreeRequired: true, council: true, minYears: 3, specificExperience: [{ years: 1, context: "empreendimentos de grande porte e obras de unidades industriais" }], projectEvidence: ["identificação e tratamento de interfaces em engenharia, construção, montagem e manutenção"], notes: ["Perfil multidisciplinar."] }),
    role("quality-control-coordinator", "3.2.10.1", "Coordenador de Controle da Qualidade", ["coordenador de controle da qualidade", "coordenador da qualidade"], { group: "Qualidade", degreeAny: ["engenharia", "formação técnica", "formacao tecnica"], degreeRequired: true, council: true, minYears: 3, courses: ["ABNT NBR ISO 9001"], projectEvidence: ["implantação, desenvolvimento e manutenção de Sistema de Gestão da Qualidade e controle da qualidade"] }),
    role("documentation-technician", "3.2.10.2", "Técnico de Documentação", ["técnico de documentação", "tecnico de documentacao", "document controller", "controle de documentação"], { group: "Qualidade/Documentação", degreeAny: ["técnico em mecânica", "tecnico em mecanica", "técnico em metalurgia", "tecnico em metalurgia", "técnico em soldagem", "tecnico em soldagem", "técnico em química", "tecnico em quimica"], degreeRequired: true, council: true, minYears: 3, projectEvidence: ["organização de arquivos, emissão de relatórios e montagem de data books em obras industriais"], notes: ["Conhecimentos intermediários de Word, PowerPoint e Excel."] }),
    role("inspection-coordinator", "3.2.10.3", "Coordenador de Inspeção", ["coordenador de inspeção", "coordenador de inspecao"], { group: "Qualidade/Inspeção", degreeAny: ["formação técnica", "formacao tecnica"], degreeRequired: true, council: true, minYears: 5, projectEvidence: ["coordenação/supervisão de inspeção em obras de construção de unidades de processo"] }),
    role("equipment-inspector-quality", "3.2.10.4", "Inspetor de Equipamentos – Qualidade", ["inspetor de equipamentos", "inspetor de equipamento"], { group: "Qualidade/Inspeção", minYears: 5, credentials: ["Portaria INMETRO nº 537/2015", "ABRAMAN PNQC-NR-P4.10-12"], projectEvidence: ["inspeção de equipamentos de unidades de processo"] }),
    role("nr10-qualified", "3.2.10.5", "Profissional Qualificado e Habilitado em NR-10", ["profissional qualificado nr-10", "profissional habilitado nr-10", "nr-10"], { group: "Qualidade/Elétrica", council: true, credentials: ["NR-10"], projectEvidence: ["construção de unidades de processo"] }),
    role("calibration-instrumentist", "3.2.10.6 / 3.3.1.l", "Instrumentista de Calibração", ["instrumentista de calibração", "instrumentista de calibracao"], { group: "Qualidade/Instrumentação", degreeAny: ["técnico em instrumentação", "tecnico em instrumentacao"], degreeRequired: true, council: true, minYears: 4, projectEvidence: ["calibração e testes de instrumentos e malhas em obras industriais/unidades de processo"] }),
    role("planning-engineer", "3.2.11.1", "Engenheiro de Planejamento", ["engenheiro de planejamento"], { group: "Planejamento", degreeAny: ["engenharia"], degreeRequired: true, council: true, minYears: 5, credentials: ["especialização Lato Sensu ou Stricto Sensu"], projectEvidence: ["planejamento e controle de obras de grande porte do segmento de óleo e gás"], notes: ["Conhecimento avançado nas ferramentas do Anexo VI – Diretriz de Planejamento e Controle."] }),
    role("planning-technician", "3.2.11.2", "Técnico de Planejamento", ["técnico de planejamento", "tecnico de planejamento"], { group: "Planejamento", degreeAny: ["técnico mecânico", "tecnico mecanico", "técnico eletricista", "tecnico eletricista", "técnico eletrônico", "tecnico eletronico", "técnico de edificações", "tecnico de edificacoes"], projectEvidence: ["experiência registrada em planejamento e controle"], notes: ["Conhecimento avançado nas ferramentas do Anexo VI."] }),
    role("communications-professional", "3.2.12.1", "Profissional de Comunicação e Responsabilidade Social", ["comunicação e responsabilidade social", "comunicacao e responsabilidade social", "comunicação social"], { group: "Comunicação", degreeAny: ["comunicação social", "comunicacao social"], degreeRequired: true, council: true, minYears: 2, projectEvidence: ["planejamento e execução de programas de comunicação, assessoria de imprensa, campanhas e informativos"] }),
    role("telecom-responsible", "3.2.13.1", "Responsável pelos Serviços de Telecomunicações", ["responsável telecomunicações", "responsavel telecomunicacoes"], { group: "Telecom", degreeAny: ["engenharia de telecomunicações", "engenharia de telecomunicacoes", "engenharia equivalente"], degreeRequired: true, council: true, minYears: 3, courses: ["NR-10 ou NR-35 quando requerido pelo SMS PETROBRAS"], projectEvidence: ["construção, montagem, instalação e testes de telecomunicações em unidades industriais"] }),
    role("telecom-supervisor", "3.2.13.2", "Supervisor de Montagem de Telecomunicações", ["supervisor de telecomunicações", "supervisor telecom"], { group: "Telecom", council: true, minYears: 3, specificExperience: [{ years: 1, context: "cargo de Supervisor em Montagem de Sistemas de Telecomunicações Industriais" }], courses: ["NR-10 ou NR-35 quando requerido pelo SMS PETROBRAS"] }),

    role("project-coordinator", "3.2.14.1", "Coordenador de Projeto", ["coordenador de projeto", "coordenador técnico de projeto"], { group: "Projeto", degreeAny: ["engenharia"], degreeRequired: true, council: true, minYears: 6, projectEvidence: ["projetos de Unidades Industriais", "função de gerenciamento nos últimos cinco anos"], notes: ["Deve demonstrar conhecimento amplo de todo o escopo contratual."] }),
    role("project-planning-coordinator", "3.2.14.2", "Coordenador de Planejamento do Projeto Executivo", ["coordenador de planejamento do projeto", "coordenador planejamento projeto executivo"], { group: "Projeto", degreeAny: ["engenharia"], degreeRequired: true, council: true, minYears: 6, credentials: ["PMP ou MBA em Gestão de Projetos – desejável"], projectEvidence: ["coordenação de planejamento de projeto de obras industriais"] }),
    role("automation-instrumentation-lead", "3.2.14.3", "Líder de Disciplina de Automação/Instrumentação", ["líder automação instrumentação", "lider automacao instrumentacao", "líder de instrumentação"], { group: "Projeto", degreeAny: ["engenharia elétrica", "engenharia eletrica", "engenharia eletrônica", "engenharia eletronica", "engenharia de automação", "engenharia de automacao"], degreeRequired: true, council: true, minYears: 5, projectEvidence: ["liderança na especificação de SIS/controle em pelo menos um projeto de refinaria/petroquímica", "supervisão de equipe em pelo menos dois projetos industriais"], notes: ["Outras engenharias podem ser aceitas com pós-graduação em Automação ou Instrumentação."] }),
    role("functional-safety-specialist", "3.2.14.4", "Profissional de Segurança Funcional", ["segurança funcional", "seguranca funcional", "especialista sis"], { group: "Projeto", credentials: ["certificação IEC-61511 ou experiência em pelo menos 2 projetos com responsabilidade pelos cálculos de SIS"], projectEvidence: ["SRS e documentação SIS até CONFORME CONSTRUÍDO"] }),
    role("automation-specialist", "3.2.14.5", "Especialista em Automação", ["especialista em automação", "especialista em automacao"], { group: "Projeto", degreeAny: ["nível superior", "nivel superior"], degreeRequired: true, council: true, minYears: 5, projectEvidence: ["projetos de automação de Unidades Industriais de grande porte com as tecnologias do contrato"] }),
    role("static-equipment-lead", "3.2.14.6", "Líder de Disciplina de Equipamentos Estáticos", ["líder equipamentos estáticos", "lider equipamentos estaticos"], { group: "Projeto", degreeAny: ["engenharia mecânica", "engenharia mecanica"], degreeRequired: true, council: true, minYears: 5, projectEvidence: ["liderança em projeto de caldeiraria para refinaria/petroquímica", "especificação/análise de equipamentos em pelo menos um projeto", "supervisão de equipe em pelo menos dois projetos"] }),
    role("dynamic-equipment-lead", "3.2.14.7", "Líder de Disciplina de Equipamentos Dinâmicos", ["líder equipamentos dinâmicos", "lider equipamentos dinamicos"], { group: "Projeto", degreeAny: ["engenharia mecânica", "engenharia mecanica"], degreeRequired: true, council: true, minYears: 5, projectEvidence: ["liderança em pelo menos um projeto para refinaria/petroquímica", "seleção/especificação/análise em pelo menos três projetos", "supervisão de equipe em pelo menos dois projetos"] }),
    role("compressor-specialist", "3.2.14.8", "Especialista em Compressores", ["especialista em compressores", "especialista compressor"], { group: "Projeto", degreeAny: ["engenharia mecânica", "engenharia mecanica"], degreeRequired: true, council: true, minYears: 6, projectEvidence: ["detalhamento de compressores para unidades industriais de óleo e gás"] }),
    role("civil-discipline-lead", "3.2.14.9", "Líder de Disciplina de Civil", ["líder de civil", "lider de civil", "líder disciplina civil"], { group: "Projeto", degreeAny: ["engenharia civil"], degreeRequired: true, council: true, minYears: 8, projectEvidence: ["liderança/supervisão de equipe em pelo menos três projetos civis de refino, petroquímica, gás ou energia"] }),
    role("geotechnical-specialist", "3.2.14.10", "Especialista em Geotecnia/Fundações/Terraplenagem/Pavimentação", ["especialista em geotecnia", "especialista em fundações", "especialista terraplenagem", "especialista pavimentação"], { group: "Projeto", degreeAny: ["engenharia civil"], degreeRequired: true, council: true, minYears: 8, projectEvidence: ["pelo menos três projetos de geotecnia/fundações/terraplenagem/pavimentação em obras de grande porte"] }),
    role("structures-specialist", "3.2.14.11", "Especialista em Estruturas", ["especialista em estruturas"], { group: "Projeto", degreeAny: ["engenharia civil"], degreeRequired: true, council: true, minYears: 8, projectEvidence: ["pelo menos três projetos de estruturas em unidades de refino, petroquímica, gás ou energia"] }),
    role("drainage-lead", "3.2.14.12", "Líder de Drenagem e Instalações Hidráulico-Sanitárias", ["líder de drenagem", "lider de drenagem", "instalações hidráulico sanitárias"], { group: "Projeto", degreeAny: ["engenharia civil"], degreeRequired: true, council: true, minYears: 8, projectEvidence: ["pelo menos três projetos de drenagem e instalações hidráulico-sanitárias em refino, petroquímica, gás ou energia"] }),
    role("architecture-lead", "3.2.14.13", "Líder da Disciplina de Arquitetura", ["líder de arquitetura", "lider de arquitetura", "arquiteto líder"], { group: "Projeto", degreeAny: ["arquitetura"], degreeRequired: true, council: true, minYears: 5, projectEvidence: ["projetos de arquitetura de unidades industriais de grande porte"] }),
    role("hvac-lead", "3.2.14.14", "Líder de Disciplina de HVAC", ["líder hvac", "lider hvac", "líder de hvac"], { group: "Projeto", degreeAny: ["engenharia mecânica", "engenharia mecanica"], degreeRequired: true, council: true, minYears: 5, projectEvidence: ["liderança em pelo menos um projeto HVAC nos últimos 5 anos", "seleção/especificação/análise em pelo menos três projetos", "supervisão em pelo menos dois projetos"] }),
    role("electrical-lead", "3.2.14.15", "Líder de Disciplina de Elétrica", ["líder de elétrica", "lider de eletrica", "líder disciplina elétrica"], { group: "Projeto", degreeAny: ["engenharia elétrica", "engenharia eletrica"], degreeRequired: true, council: true, minYears: 5, projectEvidence: ["liderança em pelo menos um projeto de eletricidade para refinaria/petroquímica", "supervisão de equipe em pelo menos dois projetos"] }),
    role("electrical-automation-specialist", "3.2.14.16", "Especialista em Automação Elétrica", ["especialista automação elétrica", "especialista automacao eletrica", "IEC-61850"], { group: "Projeto", degreeAny: ["nível superior", "nivel superior"], degreeRequired: true, council: true, minYears: 5, projectEvidence: ["automação elétrica de unidades industriais de grande porte, especialmente IEC-61850"] }),
    role("process-lead", "3.2.14.17", "Líder de Disciplina de Processo", ["líder de processo", "lider de processo"], { group: "Projeto", degreeAny: ["engenharia química", "engenharia quimica"], degreeRequired: true, council: true, minYears: 8, projectEvidence: ["liderança em pelo menos um projeto de processo para refinaria/petroquímica", "memórias de cálculo/balanços/escoamento/especificação em pelo menos dois projetos", "pelo menos quatro projetos de processo para refinaria/petroquímica"] }),
    role("industrial-safety-lead", "3.2.14.18", "Líder de Disciplina de Segurança Industrial", ["líder de segurança industrial", "lider seguranca industrial"], { group: "Projeto", degreeAny: ["engenharia"], degreeRequired: true, council: true, minYears: 5, credentials: ["especialização em segurança"], projectEvidence: ["liderança em projeto de segurança industrial para refinaria/petroquímica", "cálculos de rede de incêndio/classificação de área/sensores em pelo menos dois projetos", "pelo menos quatro projetos de segurança industrial"] }),
    role("telecom-lead", "3.2.14.19", "Líder de Disciplina de Telecomunicações", ["líder telecomunicações", "lider telecomunicacoes"], { group: "Projeto", degreeAny: ["engenharia de telecomunicações", "engenharia de telecomunicacoes", "engenharia elétrica", "engenharia eletrica"], degreeRequired: true, council: true, minYears: 5, projectEvidence: ["liderança na especificação de telecom em pelo menos um projeto para refinaria/petroquímica", "supervisão em pelo menos dois projetos industriais"] }),
    role("piping-lead", "3.2.14.20", "Líder de Disciplina de Tubulação", ["líder de tubulação", "lider de tubulacao"], { group: "Projeto", degreeAny: ["engenharia mecânica", "engenharia mecanica"], degreeRequired: true, council: true, minYears: 8, projectEvidence: ["liderança em pelo menos quatro projetos de tubulação para refinaria/petroquímica", "supervisão em pelo menos quatro projetos", "análise/especificação de materiais em pelo menos quatro projetos"] }),
    role("flexibility-specialist", "3.2.14.21", "Especialista em Flexibilidade", ["especialista em flexibilidade", "cálculo de flexibilidade", "calculo de flexibilidade"], { group: "Projeto", minYears: 5, projectEvidence: ["cálculo de flexibilidade e suportação, com software específico, em pelo menos dois projetos de tubulações industriais"] }),
    role("cae-it", "3.2.14.22.a", "Profissional de TI – Ambiente CAE 2D/3D", ["profissional de ti cae", "administrador cae", "ambiente cae"], { group: "Projeto/CAE", projectEvidence: ["criação e gerenciamento de software/hardware para CAE 2D, AVEVA Everything3D, AVEVA GLOBAL e Oracle Primavera"] }),
    role("aveva-admin", "3.2.14.22.b", "Administrador de AVEVA Everything3D / GLOBAL", ["administrador aveva", "administrador everything3d", "administrador pdms"], { group: "Projeto/CAE", minYears: 5, projectEvidence: ["administração de AVEVA Everything3D/GLOBAL ou AVEVA PDMS em projeto de porte e complexidade similares"] }),
    role("aveva-designer", "3.2.14.22.c", "Projetista de AVEVA Everything3D / GLOBAL", ["projetista aveva", "projetista everything3d", "projetista pdms"], { group: "Projeto/CAE", minYears: 5, projectEvidence: ["projeto em AVEVA Everything3D/GLOBAL ou AVEVA PDMS em empreendimento de porte e complexidade similares"] }),
    role("remote-access-admin", "3.2.14.22.d", "Administrador de Infraestrutura de Acesso Remoto", ["administrador de acesso remoto", "administrador infraestrutura acesso remoto", "vpn site-to-site"], { group: "Projeto/CAE", degreeAny: ["engenharia de telecomunicações", "engenharia de telecomunicacoes", "engenharia eletrônica", "engenharia eletronica", "análise de sistemas", "analise de sistemas", "sistemas de informação", "sistemas de informacao", "ciência da computação", "ciencia da computacao", "engenharia da computação", "engenharia da computacao"], degreeRequired: true, council: true, minYears: 5, projectEvidence: ["configuração de VPN Site-to-Site IPSec com certificado digital", "análise e diagnóstico de conectividade"] }),
    role("comos-admin", "3.2.14.22.e", "Administrador de COMOS", ["administrador de comos", "administrador comos"], { group: "Projeto/CAE", minYears: 5, projectEvidence: ["administração COMOS ou atividade equivalente em projeto de mesmo porte e complexidade"] }),
    role("comos-designer", "3.2.14.22.f", "Projetista de COMOS", ["projetista de comos", "projetista comos"], { group: "Projeto/CAE", minYears: 5, projectEvidence: ["projeto COMOS ou atividade equivalente em projeto de mesmo porte e complexidade"] }),
    role("furnace-lead", "3.2.14.23", "Líder da Disciplina de Fornos Industriais", ["líder de fornos", "lider de fornos", "fornos industriais api 560"], { group: "Projeto", degreeAny: ["engenharia mecânica", "engenharia mecanica"], degreeRequired: true, council: true, minYears: 8, projectEvidence: ["liderança em projeto de forno API 560 para refinaria/petroquímica", "especificação/análise de propostas/RM/pareceres/documentos de fabricante em projeto de fornos", "supervisão de equipe em pelo menos um projeto"] }),
    role("purchase-coordinator", "3.2.15.1", "Coordenador de Compras", ["coordenador de compras"], { group: "Suprimentos", degreeAny: ["engenharia", "economia", "administração", "administracao"], degreeRequired: true, council: true, minYears: 8, projectEvidence: ["cargo em empreendimentos de porte similar"], notes: ["Domínio de ferramentas de gestão de suprimentos/compras."] }),
    role("expediting-coordinator", "3.2.15.2", "Coordenador de Diligenciamento", ["coordenador de diligenciamento"], { group: "Suprimentos", degreeAny: ["engenharia", "economia", "administração", "administracao"], degreeRequired: true, council: true, minYears: 8, projectEvidence: ["cargo em empreendimentos de porte similar"], notes: ["Domínio de ferramentas de gestão de suprimentos/diligenciamento."] }),

    role("ndt-inspector", "3.3.1.a", "Inspetor de Ensaios Não Destrutivos (END)", ["inspetor end", "inspetor de ensaios não destrutivos", "inspetor de ensaios nao destrutivos"], { group: "Inspeção", credentials: ["ABENDI NA-001", "ABNT NBR NM ISO 9712"], notes: ["Para serviços no exterior, aplicar PETROBRAS N-2941 com aprovação prévia da PETROBRAS.", "Se houver acesso por corda, exige no mínimo nível 1 por IRATA, ABENDI ou ANEAC."] }),
    role("welding-inspector", "3.3.1.b", "Inspetor de Soldagem", ["inspetor de soldagem"], { group: "Inspeção", credentials: ["FBTS", "ABNT NBR 14842"], notes: ["Para serviços no exterior, aplicar PETROBRAS N-2941 com aprovação prévia."] }),
    role("manufacturing-inspector", "3.3.1.c", "Inspetor de Fabricação", ["inspetor de fabricação", "inspetor de fabricacao"], { group: "Inspeção", credentials: ["ABENDI", "ABNT NBR 16278"], notes: ["Para serviços no exterior, aplicar PETROBRAS N-2941 com aprovação prévia."] }),
    role("painting-inspector", "3.3.1.d", "Inspetor de Pintura", ["inspetor de pintura"], { group: "Inspeção", credentials: ["ABRACO / SNQC-CP", "ABNT NBR 15218"], notes: ["Para serviços no exterior, aplicar PETROBRAS N-2941 com aprovação prévia."] }),
    role("insulation-refractory-tech", "3.3.1.e", "Técnico de Qualidade em Isolamentos Térmicos e Refratários", ["técnico de qualidade isolamento", "técnico refratário", "tecnico refratario"], { group: "Inspeção", council: true, credentials: ["API RP 936"], specificExperience: [{ years: 0.5, context: "isolamento térmico, inclusive com acesso por cordas" }], notes: ["Capacitação para preparação de superfície e mapeamento de janelas de inspeção."] }),
    role("concrete-control-tech", "3.3.1.f", "Técnico de Controle Tecnológico de Concreto", ["controle tecnológico de concreto", "controle tecnologico de concreto"], { group: "Inspeção", council: true, credentials: ["NQCP/IBRACON", "ABNT NBR 15146-1"], notes: ["No exterior: entidade independente conforme ISO/IEC 17024, mediante aprovação prévia da PETROBRAS."] }),
    role("dimensional-inspector", "3.3.1.g", "Inspetor de Controle Dimensional", ["inspetor de controle dimensional", "controle dimensional"], { group: "Inspeção", credentials: ["ABENDI", "ABNT NBR 15523"], notes: ["No exterior: PETROBRAS N-2941 com aprovação prévia."] }),
    role("instrumentation-electrical-inspector", "3.3.1.h", "Inspetor de Instrumentação e Eletricidade", ["inspetor de instrumentação", "inspetor de eletricidade"], { group: "Inspeção", degreeAny: ["formação na área elétrica", "formacao na area eletrica"], degreeRequired: true, council: true, credentials: ["Sistema de Certificação de Pessoas FIRJAN/SENAI"], notes: ["No exterior: PETROBRAS N-2941 com aprovação prévia."] }),
    role("civil-inspector", "3.3.1.i", "Inspetor de Construção Civil", ["inspetor de construção civil", "inspetor civil"], { group: "Inspeção", degreeAny: ["construção civil", "construcao civil"], degreeRequired: true, council: true, minYears: 5, projectEvidence: ["obras de unidades industriais"] }),
    role("quality-supervisor", "3.3.1.j", "Supervisor de Qualidade", ["supervisor de qualidade", "supervisor da qualidade"], { group: "Inspeção/Qualidade", degreeAny: ["formação técnica", "formacao tecnica"], degreeRequired: true, council: true, minYears: 5, courses: ["ISO 9001"], projectEvidence: ["Sistema de Gestão da Qualidade e controle da qualidade"], notes: ["Deve ter exercido o cargo de Supervisor da Qualidade."] }),
    role("inspection-supervisor", "3.3.1.k", "Supervisor de Inspeção", ["supervisor de inspeção", "supervisor de inspecao"], { group: "Inspeção", degreeAny: ["formação técnica", "formacao tecnica"], degreeRequired: true, council: true, minYears: 10, projectEvidence: ["coordenação/supervisão de inspeção em obras industriais petroquímicas"] }),
    role("painter-blaster", "3.5.1", "Pintor / Operador de Jato", ["pintor industrial", "operador de jato", "jateador"], { group: "Execução – Pintura", specificExperience: [{ years: 0.5, context: "experiência mínima e ininterrupta na atividade" }], notes: ["A relação de colaboradores qualificados deve ser apresentada previamente à Fiscalização."] }),
    role("systems-analyst", "3.6.1", "Analista de Sistemas", ["analista de sistemas", "engenheiro de software"], { group: "Sistemas", degreeAny: ["ciência da computação", "ciencia da computacao", "análise de sistemas", "analise de sistemas", "engenharia de software", "tecnologia da informação", "tecnologia da informacao"], degreeRequired: true, minYears: 3, projectEvidence: ["integração de sistemas", "ETLs", "painéis gerenciais", "desenvolvimento de APIs"] }),
    role("programmer", "3.6.2", "Programador", ["programador", "desenvolvedor de software", "software developer"], { group: "Sistemas", degreeAny: ["graduação em desenvolvimento de sistemas", "graduacao em desenvolvimento de sistemas", "técnico em desenvolvimento de sistemas", "tecnico em desenvolvimento de sistemas"], degreeRequired: true, minYears: 3, projectEvidence: ["desenvolvimento de software", "desenvolvimento de APIs"] }),

    role("safety-coordinator", "3.7.1.1", "Coordenador de Segurança", ["coordenador de segurança", "coordenador de seguranca"], { group: "SMS", degreeAny: ["engenharia"], degreeRequired: true, council: true, minYears: 5, credentials: ["especialização em Engenharia de Segurança do Trabalho", "CREA vigente"], courses: ["ISO 45001:2018", "ABNT NBR ISO 14001:2015"], projectEvidence: ["Sistemas de Gestão de SMS em obras de mesmo porte"] }),
    role("safety-engineer", "3.7.1.2", "Engenheiro de Segurança do Trabalho", ["engenheiro de segurança do trabalho", "engenheiro de seguranca do trabalho"], { group: "SMS", degreeAny: ["engenharia"], degreeRequired: true, council: true, minYears: 3, credentials: ["especialização em Engenharia de Segurança do Trabalho", "CREA vigente"], courses: ["ISO 45001:2018", "ABNT NBR ISO 14001:2015"], projectEvidence: ["obras industriais ou de dutos"] }),
    role("safety-technician", "3.7.1.3", "Técnico de Segurança do Trabalho", ["técnico de segurança do trabalho", "tecnico de seguranca do trabalho"], { group: "SMS", degreeAny: ["técnico em segurança do trabalho", "tecnico em seguranca do trabalho"], degreeRequired: true, minYears: 1, credentials: ["registro no Ministério do Trabalho"], courses: ["ISO 45001:2018", "ABNT NBR ISO 14001:2015"], projectEvidence: ["obras industriais ou de dutos"] }),
    role("rescuer", "3.7.1.4", "Resgatista", ["resgatista", "resgate industrial"], { group: "SMS", minYears: 3, credentials: ["ABNT NBR 15475 AC-N1/AC-N2/AC-N3 ou IRATA equivalente"], courses: ["Curso Básico de Formação de Resgatistas – mínimo 40 h"], projectEvidence: ["obras industriais e/ou petroquímicas"] }),
    role("environment-coordinator", "3.7.2.1", "Coordenador de Meio Ambiente", ["coordenador de meio ambiente"], { group: "SMS", degreeAny: ["engenharia"], degreeRequired: true, council: true, minYears: 5, credentials: ["CREA vigente"], courses: ["ISO 45001:2018", "ABNT NBR ISO 14001:2015"], projectEvidence: ["Sistemas de Gestão de SMS em obras de mesmo porte"] }),
    role("environment-professional", "3.7.2.2", "Profissional de Meio Ambiente", ["profissional de meio ambiente", "engenheiro ambiental"], { group: "SMS", degreeAny: ["engenharia ambiental"], degreeRequired: true, council: true, minYears: 1, credentials: ["CREA vigente"], courses: ["ISO 45001:2018", "ABNT NBR ISO 14001:2015"], projectEvidence: ["Gestão Ambiental de obras industriais ou de dutos"] }),
    role("environment-technician", "3.7.2.3", "Técnico de Meio Ambiente", ["técnico de meio ambiente", "tecnico de meio ambiente"], { group: "SMS", degreeAny: ["técnico em meio ambiente", "tecnico em meio ambiente"], degreeRequired: true, minYears: 1, courses: ["ISO 45001:2018", "ABNT NBR ISO 14001:2015"], projectEvidence: ["obras industriais ou de dutos"] }),
    role("health-coordinator", "3.7.3.1", "Coordenador de Saúde (SMS)", ["coordenador de saúde", "coordenador de saude"], { group: "Saúde", degreeAny: ["medicina"], degreeRequired: true, council: true, minYears: 5, credentials: ["CRM vigente"], courses: ["ISO 45001:2018", "ABNT NBR ISO 14001:2015"], projectEvidence: ["Sistemas de Gestão da Saúde em obras de mesmo porte"] }),
    role("occupational-physician", "3.7.3.2", "Médico do Trabalho", ["médico do trabalho", "medico do trabalho"], { group: "Saúde", degreeAny: ["medicina"], degreeRequired: true, council: true, minYears: 3, credentials: ["especialização em Medicina do Trabalho", "CRM vigente"], courses: ["Atendimento Pré-hospitalar de Emergência em Trauma – mínimo 20 h presenciais"], notes: ["Retreinamento e recertificação a cada 2 anos."] }),
    role("occupational-nurse", "3.7.3.3", "Enfermeiro do Trabalho", ["enfermeiro do trabalho", "enfermagem do trabalho"], { group: "Saúde", degreeAny: ["enfermagem do trabalho", "enfermagem"], degreeRequired: true, council: true, minYears: 3, credentials: ["especialização em Enfermagem do Trabalho", "COREN vigente"], courses: ["Atendimento Pré-hospitalar de Emergência em Trauma – mínimo 20 h presenciais"], notes: ["Retreinamento e recertificação a cada 2 anos."] }),
    role("occupational-nursing-technician", "3.7.3.4", "Técnico de Enfermagem do Trabalho", ["técnico de enfermagem do trabalho", "tecnico de enfermagem do trabalho"], { group: "Saúde", degreeAny: ["enfermagem do trabalho"], degreeRequired: true, council: true, minYears: 3, credentials: ["COREN vigente"], courses: ["Atendimento Pré-hospitalar de Emergência em Trauma – mínimo 20 h presenciais"], notes: ["Retreinamento e recertificação a cada 2 anos."] }),
    role("nursing-assistant", "3.7.3.5", "Auxiliar de Enfermagem", ["auxiliar de enfermagem"], { group: "Saúde", degreeAny: ["curso de formação técnica", "curso de formacao tecnica"], degreeRequired: true, council: true, minYears: 1, credentials: ["COREN vigente"] }),
  ]);

  const ROLE_BY_ID = Object.freeze(Object.fromEntries(ROLES.map((item) => [item.id, item])));

  function supplementalFor(roleItem) {
    if (!roleItem) return [];
    const group = String(roleItem.group || "").toLowerCase();
    const title = String(roleItem.title || "").toLowerCase();
    const ids = new Set(["ET-5290.00-22000-910-1LV-004"]);
    if (group.includes("inspe") || title.includes("inspetor") || title.includes("inspeção")) ids.add("ET-0000.00-0000-972-PEI-003");
    if (title.includes("válvula") || title.includes("valvula")) ids.add("ET-5290.00-2000-971-PEI-005");
    if (group.includes("inspe") || title.includes("inspetor")) ids.add("MD-5290.00-22313-950-1LV-007");
    return SUPPLEMENTAL_SOURCES.filter((source) => ids.has(source.id));
  }

  return Object.freeze({ SOURCE, SUPPLEMENTAL_SOURCES, GENERAL, ROLES, ROLE_BY_ID, supplementalFor });
});
